### ISSUE TITLE
How to use with with a Form with many Text Inputs?

### ISSUE THREAD

**Issue by tezlopchan** [hodgef/react-simple-keyboard#1]
I wanted to fix the react simple keyboard at the bottom of my react app and then use it as a keyboard for all the inputs in whole app.

Also want to keep the input focus while typing.

**Comment by hodgef** [comment]
Hello tezlopchan, just letting you know that I'm looking into this.
I have a few ideas but I think it's best if I get you a fully working example.

I'll update this thread in a bit!

**Comment by hodgef** [comment]
Hello @tezlopchan,

I've just released a feature called "inputName" in 1.2.5 that should resolve your issue.
The guide is here: https://github.com/hodgef/react-simple-keyboard#using-several-inputs

Hopefully this solves it. If not, feel free to let me know !

Thanks,
Francisco Hodge
