### ISSUE TITLE
Set size of keyboard

### ISSUE THREAD

**Issue by takeitbillykyle** [hodgef/react-simple-keyboard#1014]
Hey,
right now the keyboard is taking the full width of the parent component. Is there a way to rescale the keyboard? I've tried setting a fixed width/height as well as putting it inside a rescalabe Container, but it did now work.

**Comment by hodgef** [comment]
Hello @takeitbillykyle,

The keyboard's width is part of the default theme (applied automatically when you don't define a `theme` option).

To change it, simply edit `.simple-keyboard.hg-theme-default` in your CSS.

![image](https://user-images.githubusercontent.com/25509135/107600026-7558a980-6bf0-11eb-8d92-12bfc00644f8.png)

Regards,
Francisco Hodge
