### ISSUE TITLE
Using modules ?

### ISSUE THREAD

**Issue by NoMaillard** [hodgef/react-simple-keyboard#1058]
Hello, i'm trying to setup `react-simple-keyboard` with `simple-keyboard-key-navigation` but i can't find any documentation on how to set it up. here's how i tried doing it:

```tsx
import KeyboardReact from 'react-simple-keyboard';
import Keyboard from 'react-simple-keyboard';
import keyNavigation from 'simple-keyboard-key-navigation';
import 'react-simple-keyboard/build/css/index.css';

<Keyboard
  keyboardRef={(r) => (keyboardRef.current = r)}
  layoutName={layoutName}
  enableKeyNavigtion={true}
  modules={[keyNavigation]}
  debug={true}
  layout={{
    default: ['é è'],
    shift: ['É'],
  }}
  onChange={onChange}
  onRender={() => console.log('Rendered')}
/>
```

but when i press a key, i get this error

![image](https://user-images.githubusercontent.com/3889625/110329786-5bf32380-801d-11eb-8961-b22709560a57.png)

i also see in the log taht there are no logs related to the keyNavigation  module

![image](https://user-images.githubusercontent.com/3889625/110329913-7c22e280-801d-11eb-9351-1a4dcb471edd.png)

So my question is, how do you setup modules using react ?

**Comment by hodgef** [comment]
Hey @NoMaillard,

In the [docs page for simple-keyboard-key-navigation](https://hodgef.com/simple-keyboard/modules/key-navigation/) there's a React demo, although it is in the form of a Class component.

https://hodgef.com//simple-keyboard/editor/?d=simple-keyboard/react-simple-keyboard-key-navigation-demo

One key part of that demo is ensuring the module is loaded by using `onModulesLoaded`:

```jsx
<Keyboard
    keyboardRef={(r) => (this.keyboard = r)}
    layoutName={this.state.layoutName}
    onChange={this.onChange}
    onKeyPress={this.onKeyPress}
    modules={[keyNavigation]}
    enableKeyNavigation={true}
    onModulesLoaded={(keyboard) => {
    console.log(keyboard.modules);
        /**
          * Now you can use:
          * keyboard.modules.keyNavigation.up();
          * etc.
          */
        keyboard.modules.keyNavigation.down();
        keyboard.modules.keyNavigation.right();
        keyboard.modules.keyNavigation.press();
    }}
/>
```

Hope it helps!
Francisco Hodge

**Comment by NoMaillard** [comment]
@hodgef 

hi, i found out that the module is not initialized when the component loads, so i ended up writing it like this:

```tsx
// in my eventHandler

          keyboardRef.current?.modules?.keyNavigation.left();
//

        <Keyboard
          keyboardRef={(r) => (keyboardRef.current = r)}
          layoutName={layoutName}
          enableKeyNavigtion={true}
          modules={[keyNavigation]}
          onModulesLoaded={(keyboard: any) => {
            keyboard.modules.keyNavigation.init();
          }}
          debug={true}
          layout={{
            default: ['é è'],
            shift: ['É'],
          }}
          onChange={onChange}
        />
```

**Comment by hodgef** [comment]
Interesting. I'll take some time to double check modules during my work for [Version 3.0](https://github.com/hodgef/simple-keyboard/issues/920). Thanks for the heads up!
