### ISSUE TITLE
Input field text has some text, typing first time using react-simple-keyboard clears the input field and starts from first letter

### ISSUE THREAD

**Issue by iphalgun** [hodgef/react-simple-keyboard#1090]
The issue is when I'm having some text in an input field, and then when I open the react-simple-keyboard, and enter the first character using this keyboard -> The input field gets cleared and starts from the character which I entered. 

Ideally, it should start entering the character after the present text in the input field but it clears the string and starts from that entered character.

***For Example
1. I'm having an input field and a button.
2. The input field is already having a string - "Default"
3. When I focus on the keyboard, it opens the onscreen keyboard
4. When I enter the first character(for example, 'a') using the onscreen keyboard, it removes the present string "Default" and starts writing from "a". 
5. Ideally, it should add the entered character after "Default" and should look like "Defaulta"

What could be the issue?

**Comment by hodgef** [comment]
Hello @iphalgun,

Please refer to this solution: https://github.com/hodgef/react-simple-keyboard/issues/757#issuecomment-689077466

Regards,
Francisco Hodge

**Comment by iphalgun** [comment]
Thanks @hodgef
