### ISSUE TITLE
Proper way to use a common keyboard for 4 input fields in class based component

### ISSUE THREAD

**Issue by iphalgun** [hodgef/react-simple-keyboard#1096]
How can I use a common keyboard for 4 input fields efficiently in class based component?

Also, getting this error :
![Screenshot 2021-03-26 at 3 51 07 PM](https://user-images.githubusercontent.com/54344156/112617528-1622c180-8e4b-11eb-828c-e175822b93d8.png)

How can I resolve this?

**Comment by hodgef** [comment]
Hello @iphalgun,

To handle multiple inputs you'd need to use the `inputName` option. Here's some more information regarding this:
https://hodgef.com/simple-keyboard/questions-answers/use-simple-keyboard-multiple-inputs/

About the error you're getting, could you provide more details? For example, if you can explain what you're doing to get it and perhaps share a code example that'd be helpful.

For now I can't do much with the information that I have, but I'll reopen this ticket once I get more details,

Regards,
Francisco Hodge

**Comment by iphalgun** [comment]
Hi @hodgef,

Thanks for your support!

About the error I'm getting, below are some details about it:
1. I'm a modal having an input field and a button named "Save".
2. When modal opens, the keyboard is also displayed
3. Input field has some input by default
4. Now, if I click on the input field and then start typing, I get this TypeError
5. If I do not click on the input field and directly start to type, it works fine but when I click on input field then it gives this error

Should I add more details for this?

**Comment by hodgef** [comment]
Hello @iphalgun,

Sadly, I can't tell what the issue is despite the explanation. I think I'll need a repro to debug this issue. 

Could you provide a test github repository that shows the issue?

Regards,
Francisco Hodge
