### ISSUE TITLE
Backspace doesn't delete the existing value in the field by character. Instead, it deletes the entire text. 

### ISSUE THREAD

**Issue by Aravind4626** [hodgef/react-simple-keyboard#1133]
**Simple-keyboard version**
version: 2.5.186
**Describe the bug**
I tried to add getInput("inputName") and setInput("MyValue")to the keyboard for having a sync whenever that field is selected. I referred the documentation as well. However, it doesn't work as expected. My problem is when I handle multiple Inputs and switch from one field to another field, it works perfectly since the keyboard is opened all the time. But, when I close and reopen the keyboard and focus on the field that has existing value, it doesn't append the new value with the existing value. Instead, it replaces completely with the new value. 

I have been trying to solve for so long but couldn't. Can you give me a solution with explanation?

**Comment by hodgef** [comment]
Hello @Aravind4626 !

Here's a fix for your sandbox: https://codesandbox.io/s/compassionate-leaf-78g3u?file=/src/index.js

Note: Please make sure to update to react-simple-keyboard@3.0.44 (latest) as well. This version fixes a caret reset issue I noticed while debugging the sandbox.

Regards,
Francisco Hodge
