### ISSUE TITLE
Keyboard is not working correctly when put inside a dialog

### ISSUE THREAD

**Issue by khairaf** [hodgef/react-simple-keyboard#1169]
**React-simple-keyboard version**
3.0.70

**Describe the bug**
Hi, I am having this issue. I set an initial value for the input. Then, backspace not working first time opening the dialog, unless clicking on other keys, and also, typing first time clears the initial value.
I put [sandbox here](https://codesandbox.io/s/formdialog-material-demo-forked-2s3tp?file=/demo.tsx)

**Comment by hodgef** [comment]
Check out this ticket for a solution: https://github.com/hodgef/simple-keyboard/issues/858

Regards,
Francisco Hodge

**Comment by khairaf** [comment]
oh, I get it now. need to use `onInit` option. Thank you very much @hodgef
