### ISSUE TITLE
Ability to pass react components in the display object

### ISSUE THREAD

**Issue by nsharma1396** [hodgef/react-simple-keyboard#1204]
**Is your feature request related to a problem? Please describe.**
Great work on the package! However, I stumbled upon the use case of passing a React Component to the display option, something like this:

```
    <Keyboard
        ...
        display={{
          "{bksp}": <BackspaceIcon />,
          "{add}": <PlusIcon />,
          "{clearAll}": <ClearAll />,
          "{enter}": "=",
        }}
        ...
     />
```

**Describe the solution you'd like**
A possible solution would be to allow the passing/cloning of components inside the keyboard.
One implementation challenge that I can see is that the display logic is written over [here](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/Utilities.ts#L136) which essentially takes it 'outside' of react. 

**Describe alternatives you've considered**
I understand that there are challenges with passing the component as mentioned in #6. As mentioned in the same issue, the alternatives the can be considered are:
1. Passing an image instead of the custom component, I am not sure how can that be achieved if the images are stored in the codebase since the react way would be to import the image and pass it in the src.
2. Using CSS classes to achieve similar functionality would solve the use case in point 1 but will not work when a developer would like to use something like an icon from an npm package.

**Additional context**
I would like to understand the challenges that you think might occur now if a feature like this is introduced. Using images is surely a good alternative, but it might not be the best solution for some scenarios according to me.

**Comment by hodgef** [comment]
Hello @nsharma1396,

react-simple-keyboard is a wrapper of [simple-keyboard](https://github.com/hodgef/simple-keyboard) (a vanilla js library), so the props you pass to react-simple-keyboard are directly passed to the vanilla js library (with very few exceptions). 

For the `display` option, simple-keyboard [assigns the value through `innerHTML`](https://github.com/hodgef/simple-keyboard/blob/0409ee337eda6482fef28c42da39f6061ab53736/src/lib/components/Keyboard.ts#L1763). This is why the `display` option won't be able to take in a component/function as a value.

I understand that this is an annoying limitation. Unfortunately though I don't see the `display` option taking in react components for the foreseeable future. The challenge is mostly maintenance. Maintaining simple-keyboard (the vanilla js version) can be quite time consuming, so if the react version starts differing from the main package then it will be even harder to maintain.

I will file this under the Enhancement Proposals section. I might revisit this when working on a major version for the package.

Regards,
Francisco Hodge

**Comment by instadrew** [comment]
Requesting this feature as well.  My organization needs the ability to render keyboard keys whose display values are custom images rendered via React components.

**Comment by hops-carlb** [comment]
I found this issue looking for a solution myself.

It turns out it's as simple as using `renderToString` from `react-dom/server`

```
    <Keyboard
        ...
        display={{
          "{bksp}": renderToString(<Backspace />)
        }}
        ...
     />
```

<img width="148" alt="image" src="https://github.com/hodgef/react-simple-keyboard/assets/156080478/3322a3f3-aa50-4158-b0be-8d73f5719da5">
