### ISSUE TITLE
hi, thx for sharing this awesome project. But after I checked the features, I have really no Idea about where to use it meaningful? Can u give me any examples, the usecase to use this tool?

### ISSUE THREAD

**Issue by vikbert** [hodgef/react-simple-keyboard#1219]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hodgef** [comment]
Hello @vikbert,

For simple-keyboard demos check out this page:
https://hodgef.com/simple-keyboard/demos/

A step by step guide can be found here:
https://hodgef.com/simple-keyboard/getting-started/react/

Regards,
Francisco Hodge

**Comment by vikbert** [comment]
@hodgef great thx for your help.
