### ISSUE TITLE
Add the possibility to change the behavior of the "click" action on an element of the candidateBox

### ISSUE THREAD

**Issue by sommoMicc** [hodgef/react-simple-keyboard#1298]
For example, I'm using the layoutCandidate to map all the accented letters. However, I can replace the letter only if it is at the end of the input value, because when I move the caret no suggestion apperars.

More in general, it would be nice to have more control on the candidatebox behaviour, and with that also on the "click" action of a candidateBoxItem

**Comment by hodgef** [comment]
Hello @sommoMicc,

Sorry for the delay. As of v3.2.0+, the CandidateBox functionality should support caret positioning.

This can be confirmed by running the following JS demo in the simple-keyboard source (should work in React too):
https://github.com/hodgef/simple-keyboard/blob/master/src/demo/CandidateBoxDemo.js

In this demo, the option [`preventMouseDownDefault`](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/) is used to keep the focus on the input.

Regards,
Francisco Hodge

**Comment by sommoMicc** [comment]
Thanks!! I'll give it a try asap!
