### ISSUE TITLE
Caret Position is null

### ISSUE THREAD

**Issue by Moranilt** [hodgef/react-simple-keyboard#1355]
**React-simple-keyboard version**
updated version to v3.2.18 and still have this bug

**Describe the bug**
I want to get current poistion of caret, but it's always equal to null. I'm using state to show the keyboard. When it's(state) true so I can show the keyboard, but caretPosition is always null in ref while showing it with state. I need it for showing caret in textarea because nowadays caret is vanishing after pressing on any key.

Here is an example. You can see ref object in console where you can see that caretPosition is not changing and always null.

You should press on button "Show keyboard" and press any key of the keyboard. Go to console and inspect ref object with caretPosition which is null.

```jsx
import React, { useRef, useState } from "react";
import Keyboard from "react-simple-keyboard";
import "react-simple-keyboard/build/css/index.css";

function App() {
  const keyboard = useRef(null);
  const [inputValue, setInputValue] = useState("");
  const [isSHowKeyboard, setIsShowKeyboard] = useState(false);

  const onChangeKeys = (input) => {
    setInputValue(input);
    console.log(input);
    console.log(keyboard.current);
    if (keyboard) {
      keyboard.current.setInput(input);
    }
  };

  return (
    <div>
      <textarea id="testInput" value={inputValue} />
      {isSHowKeyboard && (
        <Keyboard
          onChange={onChangeKeys}
          inputName="testInput"
          syncInstanceInputs={true}
          keyboardRef={(r) => (keyboard.current = r)}
        />
      )}
      <button onClick={() => setIsShowKeyboard(true)}>Show keyboard</button>
    </div>
  );
}
export default App;

```

**Screenshots**
![image](https://user-images.githubusercontent.com/22654219/124892234-5e24b900-dfe2-11eb-816c-6efe63164640.png)

**Comment by hodgef** [comment]
Hello @Moranilt,

Every time you click outside of an input, simple-keyboard will set its internal caret position to null. This is by design. A null caret position is the default, and means simple-keyboard will add characters at the end of the string.

If you want for the focus to remain in your input, check out the demos for [preventMouseDownDefault](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/).

Regards,
Francisco Hodge

**Comment by Moranilt** [comment]
> Hello @Moranilt,
> 
> Every time you click outside of an input, simple-keyboard will set its internal caret position to null. This is by design. A null caret position is the default, and means simple-keyboard will add characters at the end of the string.
> 
> If you want for the focus to stay in your input when you click the keyboard keys, check out the demo for [preventMouseDownDefault](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/).
> 
> Regards,
> Francisco Hodge

Thank you! It solved my problem.
