### ISSUE TITLE
physicalKeyboardHighlightPress does not work

### ISSUE THREAD

**Issue by eyehol3** [hodgef/react-simple-keyboard#1386]
**React-simple-keyboard version 3.2.36**

**physicalKeyboardHighlightPress does not trigger callbacks**

I expect physicalKeyboardHighlightPress to press virtual buttons when I press physical ones, but it doesn't happen. I can type text, however handleShift, onChange, onKeyPress are not triggered by physical keyboard.

**Comment by hodgef** [comment]
Hello @eyehol3,

This should be fixed as of react-simple-keyboard@3.2.43. Feel free to update and try it out.

Regards,
Francisco Hodge
