### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by andraspalasti** [hodgef/react-simple-keyboard#1390]
My question is that why is there a typescript demo in the docs if there is literally no types in this package or am i missing something?

**Comment by hodgef** [comment]
![image](https://user-images.githubusercontent.com/25509135/126806220-0722b7cb-5228-4f73-b2c6-c38ebfc7cec4.png)
![image](https://user-images.githubusercontent.com/25509135/126806387-1cf6bcb4-a216-4866-8bb5-0e18eb5f77a9.png)

**Comment by andraspalasti** [comment]
Any types does not count

**Comment by hodgef** [comment]
I'm not fully sure what you mean, but this library uses types from the main library called simple-keyboard.

![image](https://user-images.githubusercontent.com/25509135/126817809-be49f408-ac95-41b9-9a8c-54ffb186ebce.png)

![image](https://user-images.githubusercontent.com/25509135/126817910-51ea8321-d4a2-4858-87be-557f21676db6.png)

Now I'm going to lock this to prevent a time-consuming back and forth, but if you feel there's something wrong you can be more specific or use something else.

Regards,
Francisco Hodge
