### ISSUE TITLE
React Hooks + Typescript demo not working with current versions

### ISSUE THREAD

**Issue by igorbga** [hodgef/react-simple-keyboard#1534]
Is just to address that the demo that showcases how to use the keyboard with React Hooks and Typescript seems to be outdated.

It is written as if simple-keyboards React components were still class components and they aren't.
This causes some type errors that might not be obvius to solve at first view and specially causes some doubt about if something should be done instead of "keyboar.current.setInput" call in the onChangeEvent call.

In functional components we don't have such function and indeed everything seems to work ok without calling it.

Updating it would be very helpful.

**Comment by hodgef** [comment]
Hello @igorbga,

react-simple-keyboard is a wrapper of [simple-keyboard](https://github.com/hodgef/simple-keyboard) (the vanilla JS version). As such, I don't plan to change this React wrapper in a way that would make it diverge too much from the source.

That being said, if you encounter any errors, please feel free to reach out on here [or on Discord](https://discordapp.com/invite/SJexsCG) and I will be glad to help. Having issues tracked will also help others who use search to find a solution.

Thanks,
Francisco Hodge
