### ISSUE TITLE
Japansese keyboard missing あ symbol

### ISSUE THREAD

**Issue by The-Code-Monkey** [hodgef/react-simple-keyboard#1636]
I was just checking the demo for a use case and the japanese keyboard is missing the あ symbol might be missing others.

**Comment by The-Code-Monkey** [comment]
Actually there are loads of keys missing that should be on the number keys 

![image](https://user-images.githubusercontent.com/31218527/142615005-bccdc60e-90d5-4d68-ada9-4ad9a050971b.png)

**Comment by hodgef** [comment]
Hello @The-Code-Monkey,

The languages provided in simple-keyboard-layouts only support the default layout and the shift layout. If you would like to accommodate for a third layout you can copy the [japanese layout option](https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/japanese.ts) and turn it into your desired solution.

Regards,
Francisco Hodge

**Comment by The-Code-Monkey** [comment]
My point is that your missing half the characters in your keyboard so it doesn't work at all, you can't even write hello.

Imagine a the UK keyboard without 5 characters you couldn't use it.

**Comment by hodgef** [comment]
I understand what you mean. Initially we had those characters but a request came in that numbers were missing:

https://github.com/simple-keyboard/simple-keyboard-layouts/commit/e4a12657b8c2bab6c3d5d84f276c31cc343462dc

If you want to be unblocked you can use the previous layout: https://codesandbox.io/s/zealous-hellman-m1s66?file=/src/index.js. That is until I figure out a better way to accommodate keys on the numbers row, but sadly it might take a while.

Thanks,
Francisco Hodge
