### ISSUE TITLE
How to use the modern version of the keyboard for typescript?

### ISSUE THREAD

**Issue by Fredleig** [hodgef/react-simple-keyboard#1647]
**React-simple-keyboard version**
```
    "react-simple-keyboard": "^3.3.38",
    "simple-keyboard": "^3.3.27",
```

**Describe the bug**
error import [codesandbox](https://codesandbox.io/s/elated-glitter-7w477?file=/src/App.tsx)

**Comment by hodgef** [comment]
Hey @Fredleig,

I have added a fix for this in v3.4.1. Could you give it a try? You only need react-simple-keyboard (it already includes simple-keyboard).

Demo: https://codesandbox.io/s/unruffled-bouman-i2k2g?file=/src/App.tsx

Let me know if it still doesn't work for you.

Regards,
Francisco Hodge

**Comment by Fredleig** [comment]
> Я добавил исправление для этого в v3.4.1. Не могли бы вы попробовать? Вам нужна только реакция-простая-клавиатура (она уже включает простую клавиатуру).
In react-simple-keyboard no types for simple-keyboard
[codesandbox](https://codesandbox.io/s/elated-glitter-7w477?file=/src/App.tsx)
> Сообщите мне, если это по-прежнему не работает для вас.
> All cool. Works.
