### ISSUE TITLE
Keyboard Key Size

### ISSUE THREAD

**Issue by SaMs-Hub** [hodgef/react-simple-keyboard#1660]
**Is your feature request related to a problem? Please describe.**
Problem with using the React version of the Keyboard, Want to change the size of specific keys

**Describe the solution you'd like**
Being able to change the size of keys provided.

- Current usage of the keyboard

![KeyboardSize](https://user-images.githubusercontent.com/76864645/145026673-27a35d1c-98b4-455a-87d0-dc82059e3703.jpg)

- Expected key size manipulation like

 ![ExpectedKeyboard](https://user-images.githubusercontent.com/76864645/145027159-fb700331-61ac-44a5-b5f2-77d8e1f81dc3.jpg)

**Comment by hodgef** [comment]
Hey @SaMs-Hub,

You just need to inspect the keyboard and make CSS changes where you see fit. For instance: the default theme stretches the keys using `flex-grow: 1`. If you don't want that you can change this with CSS.

![image](https://user-images.githubusercontent.com/25509135/145150871-f8685d55-80f1-4538-b2bf-a115b25dbe7d.png)

Now, if your desired theme is very different than the default one, then you can create your own theme. Check out the following item for details:

https://github.com/hodgef/simple-keyboard/issues/63#issuecomment-484515567

Thanks,
Francisco Hodge

**Comment by SaMs-Hub** [comment]
Thank You!
