### ISSUE TITLE
Export simple-keyboard typings please

### ISSUE THREAD

**Issue by bradleygore** [hodgef/react-simple-keyboard#1662]
### Issue
Although `react-simple-keyboard` includes `simple-keyboard` under the hood, the typings for `simple-keyboard` appear to get lost to the consumer. I have to pull in `simple-keyboard` separately just to import the `Keyboard` type so that TypeScript compiler knows there is a `setInput`, etc... on the `ref` returned from `react-simple-keyboard` component.

### Proposed Resolution
Export the types from contained `simple-keyboard` so that consumers using TypeScript don't have to import `simple-keyboard` separately just for the typings.
**Describe alternatives you've considered**

I believe we can just `export * from 'simple-keyboard` in the main `build/index.d.ts` file. If you're ok with this, I'm happy to submit a PR  😄 

Thanks so much!!

**Comment by hodgef** [comment]
Hey @bradleygore,

I recommend using `KeyboardReactInterface`, for example:

```jsx
import React, { useEffect, useRef } from "react";
import Keyboard, { KeyboardReactInterface } from "react-simple-keyboard";
import "./App.css";

function App() {
  const keyboard = useRef(null) as React.MutableRefObject<null | KeyboardReactInterface>;

  useEffect(() => {
    keyboard.current?.setInput("Hello");
    console.log(keyboard.current?.getInput());
  }, []);

  return (
    <div className="App">
      <Keyboard
        keyboardRef={(r: KeyboardReactInterface) => (keyboard.current = r)}
      />
    </div>
  );
}

export default App;
```

Regards,
Francisco Hodge

**Comment by bradleygore** [comment]
Hey @hodgef 

I still have to install `simple-keyboard` as far as I can tell. Maybe I'm missing something? Here's what I'm seeing:

Using a ref like this: `const keyboardRef = useRef<KeyboardReactInterface>();`

The `setInput` function (as well as any other `Keyboard` functions) is missing from the ref:
<img width="711" alt="Screen Shot 2021-12-09 at 8 22 55 AM" src="https://user-images.githubusercontent.com/5077928/145414212-72af8a77-aaa9-4f19-9cad-62c598165f21.png">

Yes, `KeyboardReactInterface` does extend `Keyboard` - but the problem is that unless I also have `react-keyboard` installed locally TS can't find the typing for it because the typing for it is not included in `react-simple-keyboard` as far as I can tell:
<img width="636" alt="Screen Shot 2021-12-09 at 8 23 27 AM" src="https://user-images.githubusercontent.com/5077928/145414444-00f1b96d-c991-4c7a-b40c-e8833ca3d41f.png">

So the final output from `react-simple-keyboard` references the typing for a thing in `simple-keyboard` that does not ship with `react-simple-keyboard`, so TS can't find the typing unless consumers install `simple-keyboard` as well.

If this is how it should work, that's fine. But other issues seemed to indicate we do not need to install `simple-keyboard` alongside `react-simple-keyboard`. 

Thanks so much 😄

**Comment by hodgef** [comment]
@bradleygore Thanks for the details! This is not intended - will fix later today

**Comment by hodgef** [comment]
Hey @bradleygore,

I've pushed a change to react-simple-keyboard@3.4.10 which should fix the issue. Feel free to give it a try!

Regards,
Francisco Hodge

**Comment by bradleygore** [comment]
Hey @hodgef - it works perfectly now! Thanks so much 😄
