### ISSUE TITLE
Accent doesn't work

### ISSUE THREAD

**Issue by henriquematiasb** [hodgef/react-simple-keyboard#1695]
**React-simple-keyboard version** 
^3.4.19

**Describe the bug**

When you press shift, any accent key and a letter, the letter does not acquire the desired accent. I didn't find anything in the documentation about this.

Expected behavior: *shift*  +  *^*  +  *e* = **ê**
Received behavior:  *shift*  +  *^*  +  *e* = **^e**

Thanks in advance

**Comment by hodgef** [comment]
Hello @henriquematiasb, this is not something supported by default. To support this, I recommend using unicode combining characters in your layout: https://en.wikipedia.org/wiki/Combining_character

Another option is to configure [layout candidates](https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/) with your desired combos.

Regards,
Francisco Hodge
