### ISSUE TITLE
Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by ricardober93** [hodgef/react-simple-keyboard#1743]
**React-simple-keyboard version**
I installed the react simple keyboard 3.4.0 and i have this error

**Describe the bug**
i think that the build has a error type

**Screenshots**
https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/react-simple-keyboard-typescript-hooks/tree/master

**Comment by hodgef** [comment]
Should be fixed as of v3.4.44. Thank you
