### ISSUE TITLE
Unable to hold down the backspace button

### ISSUE THREAD

**Issue by ikevinws** [hodgef/react-simple-keyboard#1756]
**React-simple-keyboard version**
3.4.51

**Describe the bug**
https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-preventmodefault-caret-pos/tree/master/
I am unable to hold down the backspace button. Sometimes it works but it seems to only occur when controlling the caretPosition.

**Comment by hodgef** [comment]
Hello @ikevinws, thanks for raising this. I have reverted one caret positioning change that might have caused this.

Feel free to try out react-simple-keyboard@3.4.52 and let me know if you can still repro the issue.

Regards,
Francisco Hodge

**Comment by ikevinws** [comment]
@hodgef Thanks, the problem has been fixed on the latest version.
