### ISSUE TITLE
React-simple-keyboard with simple-keyboard-layouts is throwing error

### ISSUE THREAD

**Issue by ikevinws** [hodgef/react-simple-keyboard#1776]
**React-simple-keyboard version**
3.4.58

**simple-keyboard-layouts version**
3.1.48

**Describe the bug**
https://codesandbox.io/s/delicate-lake-jjd23?file=/src/index.js
I am getting an error when using simple-keyboard-layouts v3.1.48. Changing simple-keyboard-layouts to v1.15.172 fixes the issue.

![Screenshot from 2022-02-11 12-09-04](https://user-images.githubusercontent.com/44091034/153636635-2c0a033c-1dcf-4ad2-85fb-df2f9634626d.png)

**Comment by hodgef** [comment]
Hello @ikevinws,

simple-keyboard-layouts usage has change since [v3.0.0](https://github.com/hodgef/react-simple-keyboard/releases/tag/3.0.0). Usage is as follows:

```js
<Keyboard
  keyboardRef={(r) => (this.keyboard = r)}
  layoutName={this.state.layoutName}
  onChange={this.onChange}
  onKeyPress={this.onKeyPress}
  {...korean}
/>
```
https://codesandbox.io/s/funny-golick-zkb9z

Regards,
Francisco Hodge
