### ISSUE TITLE
onChangeAll not getting triggered.

### ISSUE THREAD

**Issue by sprathu** [hodgef/react-simple-keyboard#1791]
**React-simple-keyboard version**
3.2.39 on Chrome

**Describe the bug**
`onChangeAll` is not getting triggered on the first page load. But it gets triggered if we refresh the page.
The first screenshot depicts the case when the `onChangeAll` is not getting triggered (the faulty case)
The second screen shot depicts the case when the `onChangeAll` is getting triggered (the working case)
The screenshots below that depicts the issue related to non passive listener for the `touchstart` event in the index.js file
**Screenshots**
When `onChangeAll` is not getting triggered
![Screenshot from 2022-02-22 16-15-14](https://user-images.githubusercontent.com/56560917/155220775-30a78ee5-2379-4a94-8158-f700ffef18ef.png)

When `onChangeAll` is getting triggered.
![Screenshot from 2022-02-22 16-15-30](https://user-images.githubusercontent.com/56560917/155220784-a54a8584-e27c-4ce7-8763-e3e26778dbd5.png)

![Screenshot from 2022-02-22 16-18-54](https://user-images.githubusercontent.com/56560917/155221135-f5e1b321-d9b1-4a36-bd88-e3ef22c19da8.png)

**Comment by hodgef** [comment]
Hey @sprathu,

- Is that on Chrome latest? I don't see those warnings on Chrome 98.
- Can you provide a repro (test git repo or sandbox example)?
- Is that on a touch device? Can you repro with a mouse?

Will reopen once I get the info above.

Regards,
Francisco Hodge

**Comment by sprathu** [comment]
https://user-images.githubusercontent.com/56560917/155384307-6af1bb0e-8384-4412-b672-7aa15a23ca15.mov

**Comment by hodgef** [comment]
@sprathu Can you repro in here? https://hodgef.com/static/simple-keyboard-test-ie.html

I haven't been able to repro in Windows. People have reported issues that only happen on Ubuntu before, such as this one https://github.com/hodgef/simple-keyboard/issues/1333#issuecomment-964956700. There are likely some differences in how Chrome is implemented across OS.

I would suggest trying with one of the following options to see if it helps:
- [useMouseEvents](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/)
- [autoUseTouchEvents](https://hodgef.com/simple-keyboard/documentation/options/autousetouchevents/)

In the meantime, I will add a Linux tag so I can revisit this when I set-up my Ubuntu VM. I'm not sure I want to add Linux-only code though, so we might need to keep relying on the options above.

Thanks,
Francisco Hodge
