### ISSUE TITLE
import 'react-simple-keyboard' not found

### ISSUE THREAD

**Issue by salman65** [hodgef/react-simple-keyboard#18]
import Keyboard from "react-simple-keyboard" raises error "Can't resolve 'react-simple-keyboard'"
I was able to import it using "import Keyboard from "react-simple-keyboard/build"".
I think either there is no root index file or some issue with linking. As a user I cannot determine from where to import the feature, Keybord. It should be linked with the root directory so that I can import it directly using library name.

**Comment by hodgef** [comment]
Hello @salman65, I'm sorry about that, i recently changed the folder name from dist back to build for consistency. But as you can see I screwed up.

I'll be pushing a fix as soon as I get in front of a computer, and will report back.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hey @salman65,

This should be resolved as of version 1.8.4. I've deprecated 1.8.3.

**Demo:** https://codesandbox.io/s/github/hodgef/demo_npm_react-simple-keyboard

Thanks again for reporting this.
