### ISSUE TITLE
clearing keyboard input

### ISSUE THREAD

**Issue by blueprintChris** [hodgef/react-simple-keyboard#1819]
Hi, 

Thanks for taking the time to create this keyboard. Just want to say I find it very useful.

I have a question which I am struggling to understand

After following your react example using the `useRef` hook to set the `keyboardRef`, I'm trying to clear the input, by calling `keyboard.current.clearInput()` but it doesn't seem to work the way I'm expecting it to.

Am I doing something wrong? Do you have any react examples of the input being cleared?

Thanks

**Comment by hodgef** [comment]
Hey @blueprintChris,

You would need to clear both the keyboard internal state and your app's state like this:
https://codesandbox.io/s/sharp-rgb-ppjy28?file=/src/index.js

If it doesn't work for you, please feel free to share more details about your implementation.

Regards,
Francisco Hodge
