### ISSUE TITLE
onKeyPress and onChange not working

### ISSUE THREAD

**Issue by ffaanngg** [hodgef/react-simple-keyboard#1824]
Hey,

So I have been trying to use this library and the `onKeyPress` prop doesn't seem to be present and `onChange` doesn't seem to be working.

This is my code
```jsx
import Keyboard from "react-simple-keyboard";
import "react-simple-keyboard/build/css/index.css";
import "../styles/keyboard.css"

export default function LayoutKeyboard(){

    const layout =  [
        "q w e r t y u i o p {bksp}",
        "a s d f g h j k l",
        "z x c v b n m {enter}",
      ]

    return <Keyboard
            theme={"hg-theme-default myTheme1"}
            display={{
              '{bksp}' : '⌫',
              '{enter}': '✔'
            }}
            onChange={console.log}
            layout={{default: layout}}
         />
}
```

I am currently using version 3.4.83 on Brave and Windows 11

![image](https://user-images.githubusercontent.com/75499121/159154444-5f16fd5c-e4ed-4407-858e-9ebe96f87e4d.png)

**Comment by ffaanngg** [comment]
By not working, I mean that nothing is being logged to console.

**Comment by hodgef** [comment]
Hello @ffaanngg,

Does this demo work for you?
https://codesandbox.io/s/fervent-dewdney-thrfti

![TEST](https://user-images.githubusercontent.com/25509135/159157082-faaa661f-196c-4200-9976-d94074f91922.gif)

If so there must be something wrong in your implementation, if you could share a reproducible example (such as a test git repo) that will help with the debugging.

Regards,
Francisco Hodge

**Comment by ffaanngg** [comment]
Thanks for the quick reply. It appears to work now when I `console.log` through a callback.
