### ISSUE TITLE
layoutCandidates for chinese layout not working

### ISSUE THREAD

**Issue by bruno-irc** [hodgef/react-simple-keyboard#1839]
I'm trying to use **layoutCandidates** option to setup a chinese keyboard, but the candidatesBox does not appear.
The keyboard works for other languages, but I can't make the **layoutCandidates** option work.
Am I using it wrong?

chinese layout object reference: https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/chinese.ts

```js
// ...
import chinese from "simple-keyboard-layouts/build/layouts/chinese";
import Keyboard from "react-simple-keyboard";
import "react-simple-keyboard/build/css/index.css";

const KeyboardContainer = ({keyboardRef}) => {

    const keyboard = useSelector(state => state.keyboard);
    
    return (
        <div style={{visibility: keyboard.show ? '' : 'hidden'}}>
            <Keyboard
                keyboardRef={r => (keyboardRef.current = r)}
                layout={chinese.layout}
                layoutCandidates={chinese.layoutCandidates}
                onChange={keyboard.onChangeMethod}
                onKeyPress={keyboard.onKeyPress}
            />
        </div>
    )
}
// ...

```

**Comment by hodgef** [comment]
Hello @bruno-irc,

This seems to be working as intended here: https://codesandbox.io/s/amazing-booth-x1vszm

![](https://user-images.githubusercontent.com/25509135/160741589-a09279c4-3b39-4f17-a7ec-f64f626aa6a6.gif)

Please feel free to provide a reproducible example if you still have the issue.

Regards,
Francisco Hodge

**Comment by AdamBartoszek** [comment]
The problem here was with: 'layout={chinese.layout}' instead of {...layout}. layoutCandidates object was not set :)
