### ISSUE TITLE
cannot stop event propogation

### ISSUE THREAD

**Issue by momin0606** [hodgef/react-simple-keyboard#1906]
i have a scenario where i need to stop propogation of event to parent component but cant in this version

**Comment by hodgef** [comment]
Hello @momin0606, Check out these options:

https://hodgef.com/simple-keyboard/documentation/options/stopmousedownpropagation/
https://hodgef.com/simple-keyboard/documentation/options/stopmouseuppropagation/

Regards,
Francisco Hodge
