### ISSUE TITLE
Are there any plans to migrate the project to react hooks?

### ISSUE THREAD

**Issue by xSNOWM4Nx** [hodgef/react-simple-keyboard#191]
After an update to React 16.9, a warning appears in the console that the method 'componentWillReceiveProps' in the KeyboardReact component will be renamed in the next major version of React.

Since the project has to be adjusted anyway, I wanted to ask if there are any plans on your part to switch everything to react hooks?

This is not a Bug. The project is still stable and running smoothly ;-)

Cheers
Daniel

**Comment by hodgef** [comment]
Hello Daniel,

Thanks for raising this. I looked at hooks but I guess I'm too used to class components!

Now that you mention it though, I'll make the switch with the next release this week :smile: 

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
There seems to be some issues after release of the new version. Will reopen

**Comment by hodgef** [comment]
Hello @xSNOWM4Nx,

After a bit of pain and debugging, version `2.0.2` is live with the [react hooks implementation](https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/Keyboard.js) 😄 

There's a breaking change though, as function components cannot have refs. I've detailed the change here:

https://github.com/hodgef/react-simple-keyboard/releases/tag/2.0.0

I've also updated the main demos and documentation. Let me know if you see something not working like it should!

Thanks,
Francisco Hodge

**Comment by xSNOWM4Nx** [comment]
Hey Francisco,

Wow. That went fast 🚀. I will look at it today or tomorrow and give you some feedback ✌️

Cheers
Daniel

**Comment by xSNOWM4Nx** [comment]
Hey Francisco,

I have downloaded the package 2.0.3 and tested my project with it. So far everything goes. But I noticed something that I would like to mention here.

- I use the package myself again in a FunctionComponent. In order for me to hold a reference to the keyboard component, I have to put it in a state, because the new prop 'keyboardRef' does not return a function. Here it would be nice if I could use the reference direct with 'useRef'. Somthing like this:
```
const myKeyboardRef = useRef<any>(undefined);
...
if (myKeyboardRef.current)
  myKeyboardRef.current.setInput(e.target.value);
...
<Keyboard
    keyboardRef={myKeyboardRef}
   .../>
```
Anyway thanks again for your commitment 👍

Cheers
Daniel

**Comment by hodgef** [comment]
Hello Daniel @xSNOWM4Nx ,

Thanks for the feedback! Regarding usage of the keyboard instance as a ref, I should have thought of that. My goal was to have the API match what we have in the [core simple-keyboard](https://github.com/hodgef/simple-keyboard) package, eg:

```
this.keyboard.setInput("Hello");
```

However I coded this again with class components in mind (for which I have tests). This was a mistake on my part.

So, to use the keyboard instance as a ref in function components, I would propose something like this:

```
const keyboard = useRef();
<Keyboard
  keyboardRef={r => keyboard.current = r}
  ...
/>
```

It's definitely not as good as what you've proposed. But I would like to avoid pushing another breaking change (and the mass editing of demos that it would require, heh).

Here's a sandbox demo that I'll publish to docs soon:
https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-hooks-demo/tree/master/

Let me know if that works for you or if you see any issues.

Thank you!
Francisco Hodge

**Comment by xSNOWM4Nx** [comment]
I've tried this before, but the 'useRef.current' prop has always been marked as read-only in TypeScript.
Properly applied, it works as suggested by you. 😉

```
const keyboard = useRef<Keyboard | null>(null);
<Keyboard
 keyboardRef={(r: Keyboard) => { keyboard.current = r }}
  ...
/>
```
That works for me.
Tank you.
