### ISSUE TITLE
caret position stays behind

### ISSUE THREAD

**Issue by grisnakh** [hodgef/react-simple-keyboard#1916]
There is a scenario, where the number has to be formatted as thousands(dots delimiters are added) gradually, the caret position is not correct but stays in the position it should be without the newly added dot.

For example,
Step 1: 1|
Step 2: 12|
Step 3: 123|
Step 4: 1.23|4

I can understand that the caret position gets incremented by one, so the dot cannot be calculated as change input value. SetCaretPosition of keyboard ref doesn't do the job for me. Also I tried to set the caretPosition of the input, but this doesn't work as expected. 

Can you propose a workaround to fix this issue?

**Comment by hodgef** [comment]
Hello @grisnakh, could you provide a repro for the issue you're seeing?

You can modify one of the demo sandboxes in the docs and share the updated link.

Will reopen once I get that, thanks!
Francisco Hodge

**Comment by grisnakh** [comment]
Hello @hodgef . Pretty fair to ask for a repro. Sorry for not providing in the first place.
So the case is here: https://codesandbox.io/s/react-simple-keyboard-demo-forked-zq6d86?file=/src/index.js

The simplest way to repro the issue, is to write 4 numbers in the integer part of the input. In the fourth digit, you will see the "miscalculation" of the caret position because the hidden keyboard input doesn't know about the formatted value.

**Comment by hodgef** [comment]
Hey @grisnakh, what I think happens is that you're modifying the input, but not syncing this value with simple-keyboard. So simple-keyboard doesn't know that there's a `.00` in the input.

To sync a value with simple-keyboard, you can call `this.keyboard.setInput(formattedInput);`

https://codesandbox.io/s/react-simple-keyboard-demo-forked-nhew3g?file=/src/index.js

Regards,
Francisco Hodge

**Comment by grisnakh** [comment]
Hi @hodgef , thanks a lot for your time. Unfortunately informing the keyboard does not fix the issue. If you see in the sandbox, the caret still stays behind when then the first demiliter for the thousand is added.

**Comment by hodgef** [comment]
@grisnakh I see - This is not supported so it's more of a feature request. The only way to fix it with the current version is to use [`disableCaretPositioning`](https://hodgef.com/simple-keyboard/documentation/options/disablecaretpositioning/) and add in the proper caret positioning logic for this use case through a [module](https://hodgef.com/simple-keyboard/modules/). Regards
