### ISSUE TITLE
Simulate/programmatically trigger physicalKeyboardHighlight

### ISSUE THREAD

**Issue by YungMilky** [hodgef/react-simple-keyboard#1998]
Thanks for your work, it's just what I needed! I'm just wondering if I can highlight a couple keys programmatically so they can be highlighted on mount.

I'm thinking something similar to this:
```
useEffect(() => {
  document.getElementById('hg-button[data-skbtn="{escape}"]').click(); // Except it should stay "clicked"
}, []);
```

**Comment by hodgef** [comment]
Hey @YungMilky,

To trigger keys programmatically you can use [`getButtonElement`](https://hodgef.com/simple-keyboard/documentation/methods/getbuttonelement/) and [`useMouseEvents`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/). This will allow you to do this:

```js
keyboard.getButtonElement("{escape}").onclick();
```

If you want them to stay highlighted, you'll need to keep track of the buttons pressed in your logic, then pass a space-separated list of these buttons to [`buttonTheme`](https://hodgef.com/simple-keyboard/documentation/options/buttontheme/). This will allow you to set a "highlighted" class of your choice for these buttons.

Feel free to explore the docs and try stuff out. If something doesn't work, you can provide a repro of the issue and I will help out.

Regards,
Francisco Hodge
