### ISSUE TITLE
Do we have option to move the input to different caret position 

### ISSUE THREAD

**Issue by rahulrsingh09** [hodgef/react-simple-keyboard#206]
Do we have option of Onscreen Left and Right Arrow [Cursor keys] for React-simple-keyboard. As i want to move the input of the character based on the left and right arrow on screen keyboard . 

Also can we map the input to a user defined input box and also at thew time of using the on screen  keyboard, does the input lose focus . ?

**Comment by rahulrsingh09** [comment]
I found out using this link that yes this library does support displaying the cursor keys using the layout

```
  let customLayout = {
    default: [
      "` 1 2 3 4 5 6 7 8 9 0 - = {bksp}",
      "{arrowleft} {arrowright}"
    ]
  }
```
But the input caret position doesn't change as we hit the left and right arrow on this keyboard , is this something that is supported currently

**Comment by hodgef** [comment]
Hello @rahulrsingh09,

These features are not currently supported so they would require custom implementation.

For the changing of the caret position, both the internal keyboard cursor (`this.keyboard.caretPosition`) and the input element's cursor would need to be in sync.

Regarding usage with the physical keyboard, I think that already is supported. For example, in the [main demo](https://franciscohodge.com/projects/simple-keyboard/demo-showcase/) you'll notice that you can type with the physical keyboard and then continue typing with simple-keyboard, and the input will be added at the right spot.

Regards,
Francisco Hodge
