### ISSUE TITLE
Typings wrong, leads to problem starting with Typescript version 4.8.3 and Node module resolution Node16 or NodeNext

### ISSUE THREAD

**Issue by gunters63** [hodgef/react-simple-keyboard#2070]
**React-simple-keyboard version**
3.4.199 or newer

**Describe the bug**
````
import { default as Keyboard } from 'react-simple-keyboard'; 
````
does not work anymore with Typescript 4.8.3 with error:
````
JSX element type 'Keyboard' does not have any construct or call signatures.ts(2604)
````

Maybe this only happens when you import react-simple-keyboard in a project where module: "EsNext" is set.

Explanation here: https://github.com/microsoft/TypeScript/issues/50690

**Comment by hodgef** [comment]
Hey @gunters63,

I cannot repro your issue with a [fresh create-react-app](https://create-react-app.dev/docs/adding-typescript/) project:

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/25509135/190879606-2455193f-0f44-41d3-940c-1cb81716cd0e.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/25509135/190879617-a496451f-cf0a-4711-8c16-feeafe7ddb09.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/25509135/190879651-651f0315-e6ef-4c95-aad8-005351fdac5d.png">

Personally, I don't use `default as ...`, in the simple-keyboard demos I always use `import Keyboard ...`.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
It seems to work even with the import style that you're using (`default as ...`):

<img width="655" alt="image" src="https://user-images.githubusercontent.com/25509135/190880347-f945922b-f0af-4563-9f77-7e7269ac11f5.png">

Try to repro with a fresh project and if it works, compare that project to yours to see where the issue is.

**Comment by gunters63** [comment]
Hi @hodgef ,

I tried to reproduce the error with a minimal create-react-app, like you.

The error happens only when you use moduleResolution Node16 or NodeNext in tsconfig,json.

You will have to change some imports for this of course, like: `import App from './App.js';`

react-simple-keyboard is not the only npm package bitten by this. See again:  https://github.com/microsoft/TypeScript/issues/50690

**Comment by gunters63** [comment]
I can try to fix this problem and create a PR?

**Comment by gunters63** [comment]
![image](https://user-images.githubusercontent.com/90346/191455797-badcbc54-6e73-42b1-a686-7f8e0ba8aabd.png)

**Comment by gunters63** [comment]
![image](https://user-images.githubusercontent.com/90346/191455976-efc47aef-e404-420a-8700-4719a9011297.png)

**Comment by hodgef** [comment]
Thanks for the details @gunters63. I will look into this, but if you have a repro to share or a PR fix that we can use it will definitely be welcomed. I will update this ticket as I delve into this.

**Comment by gunters63** [comment]
Here is the repo: https://github.com/gunters63/issue-2070, just use `npx tsc --noemit` to reproduce
I think I will give it a try to fix the issue with a PR over the weekend

**Comment by gunters63** [comment]
I don't really fully understand the implications of default exports/imports with Typescript 4.8.3 and NodeNext resolution yet (other than default exports seem to be frowned upon now :)). But an easy solution would probably be just to add this line:

````
export { KeyboardReact };
````

to index.ts and in index.modern.ts.

This enables me to import the module like this:

````
import { KeyboardReact } from "react-simple-keyboard";
````

I couldn't get it to work with default exports/imports.

**Comment by gunters63** [comment]
The following workaround works for me (see end of first comment https://github.com/microsoft/TypeScript/issues/50690#issuecomment-1241464619):

````
import { default as KeyboardBad } from 'react-simple-keyboard';
// Work around typings issue, see: https://github.com/microsoft/TypeScript/issues/50690#issuecomment-1241464619
const Keyboard = KeyboardBad as unknown as typeof KeyboardBad.default;
````

**Comment by hodgef** [comment]
Hey @gunters63, sorry for the delay.

I have pushed your proposed fix and it seems to work great:
https://github.com/hodgef/react-simple-keyboard/blob/master/build/index.d.ts#L4

Feel free to give it a try on the latest version.

Thanks!
Francisco Hodge
