### ISSUE TITLE
Duplication of onKeyPress event when using physical keyboard

### ISSUE THREAD

**Issue by idoRosen25** [hodgef/react-simple-keyboard#2109]
In my app, there is a sign in page with 2 input fields which are using a single virtual keyboard.
users might have a physical keyboard and might not (i have no control over this, depending on my client choice)
on initial navigation to the sign in page all works as expected.
However, after user logs out and redirected back to the sign in page, the physical keyboard key presses are duplicated (only with the physical keyboard, using the virtual directly is working as it should.)

any thoughts on why this behavior happens? it feels as if the onKeyPress event handler is being duplicated (when intercepting a physical keyboard click)
is there a way that the keyboard itself can identify a physical keyboard connected to the machine?

**Comment by hodgef** [comment]
Hello @idoRosen25, I don't believe this is caused by simple-keyboard. To verify, you can use Chrome/Edge Dev Tools to add a breakpoint to your `onKeyPress` and see if it's called twice.

You can also provide a repro (or test repository) of the issue, and I can take a look.

Regards,
Francisco Hodge
