### ISSUE TITLE
How to get value when I click the input box which has value

### ISSUE THREAD

**Issue by poble-pos** [hodgef/react-simple-keyboard#221]
I tried to get or patch value from input element when I click it.
It always shows blank input area even if input element has a value.

1. click input box
2. shows screen keyboard with input area
3. input some text.
4. click the input box again
5. shows screen keyboard with blank input area instead what I entered.

**Comment by hodgef** [comment]
Hello @poble-pos ,

Simple-keyboard doesn't handle input elements, it keeps an internal input. To get the internal input, you can use [`getInput()`](https://simple-keyboard.com/react/documentation/#getInput). To update the internal input, you can use [`setInput()`](https://simple-keyboard.com/react/documentation/#setInput).

If you're implementing simple-keyboard a certain way and need help, I ask that a sandbox example (repro) is provided. You can [edit this demo](https://codesandbox.io/s/github/hodgef/react-simple-keyboard-demos/tree/master/?from-embed) as to show the issue and then provide that new link. Then I'll be able to investigate what's going on.

Regards,
Francisco Hodge
