### ISSUE TITLE
newLineOnEnter not work on Safari

### ISSUE THREAD

**Issue by lhphong09t2** [hodgef/react-simple-keyboard#2217]
**React-simple-keyboard version**
3.5.14

**Describe the bug**
newLineOnEnter not work on Safari

**Comment by hodgef** [comment]
Looks fine to me, try using a `textarea` element.

![test](https://user-images.githubusercontent.com/25509135/213293577-b5c378d6-5215-45f9-8405-e080a9d554dd.gif)
