### ISSUE TITLE
Shift and Capslock buttons are not highlighted

### ISSUE THREAD

**Issue by alex-waverley** [hodgef/react-simple-keyboard#2230]
React-simple-keyboard version - 3.5.17

When the option `physicalKeyboardHighlight={true}` is used together with `physicalKeyboardHighlightPress={true}`, `Shift` or `Capslock` buttons are not highlighted. If `physicalKeyboardHighlightPress={false}` it works as expected.

![keyboard highlight issue](https://user-images.githubusercontent.com/84070515/215772482-05c6a216-455f-4918-a58f-3f494455e901.gif)

**Comment by hodgef** [comment]
@alex-waverley This is normal, actually pressing shift will result in a re-render of the layout and highlight will be lost. I don't believe this can be fixed in an optimal way.

**Comment by alex-waverley** [comment]
Thanks!
