### ISSUE TITLE
add Event to onKeyReleased callback

### ISSUE THREAD

**Issue by alex-waverley** [hodgef/react-simple-keyboard#2231]
react-simple-keyboard version - 3.5.17

When the option `physicalKeyboardHighlightPressUsePointerEvents={true}` is used, `onKeyPress` callback contains 2 arguments: button and event. Event is present if user clicks on virtual keyboard and event is `undefined` on physical one. Is it possible to add event as argument to `onKeyReleased` so that it would be easy to tell the difference between where the event comes from?

**Comment by hodgef** [comment]
Done. Thanks!

**Comment by m50S79sM6SRNp8Jn** [comment]
Can the documentation please be updated to reflect above change?
