### ISSUE TITLE
Caret issue with virtual keyboard

### ISSUE THREAD

**Issue by bohdan-krupa** [hodgef/react-simple-keyboard#2234]
Hello! I thank you for the excellent package react-simple-keyboard.

I faced one issue. I would like to see the caret when I write on the virtual keyboard but unfortunately, it hides because blur occurs after the keyboard clicks.
I played with onKeyReleased, onKeyPress, textareaRef.current.click(), textareaRef.current.focus(), setSelectionRange(), e.preventDefault(). It works in Chrome, but it doesn't work in IOS Safari.

When I created the green box that appends a symbol to a textarea and triggers .click() and .focus on the textarea after that it worked fine on IOS. And the caret was shown.

So, I would like always to see a caret in the textarea, and also after the released button in the virtual keyboard.

Maybe you could add some option like **onKeyboardButtonClick** or something like that for putting .click() and .focus on the textarea? Or Could you advise how it's better to solve that problem?

Thank you very much.

![Screenshot 2023-02-04 at 20 33 17](https://user-images.githubusercontent.com/29518768/216784451-e0d1ba94-d5af-440a-a662-578306db3911.png)

**Comment by hodgef** [comment]
Hello @bohdan-krupa,

Check out the demos for the `preventMouseDownDefault` option. There's one for React:
https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/

Regards,
Francisco Hodge
