### ISSUE TITLE
BackSpace does not work after calling replaceInput()

### ISSUE THREAD

**Issue by yudaz-brw** [hodgef/react-simple-keyboard#2282]
I use simple react-simple-keyboard with hooks

After calling replaceInput() 
the backspace does not delete 
the last character.

I use "react-simple-keyboard": "^3.4.35",

**Comment by hodgef** [comment]
Hey @yudaz-brw,

Per the [issue template](https://github.com/hodgef/react-simple-keyboard/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), I will need a sandbox repro as this helps with the debugging. Will reopen once this is provided.

Regards,
Francisco Hodge
