### ISSUE TITLE
inputPattern causes bugs.

### ISSUE THREAD

**Issue by yudaz-brw** [hodgef/react-simple-keyboard#2289]
**React-simple-keyboard version**
---------------------------------------
I use the latest version of react-simple-keyboard

**Description of the bug**
----------------------------
I use react-simple-keyboard and using the inputpattern option for
not allowing 2 blank spaces between words.
When I type 2 blank spaces I have to click twice a letter or twice 
a backspace for the input to be updated.

The code in CodeSandbox:
------------------------------
https://codesandbox.io/s/sharp-breeze-tr54fb?file=/src/App.js

**Comment by hodgef** [comment]
I initially thought that it was a bug on our end, but it appears that there was something wrong with the sandbox. Here's the fix:
https://codesandbox.io/s/dreamy-cherry-rw6uie?file=/src/App.js

Example of pressing space twice:
![image](https://user-images.githubusercontent.com/25509135/228113719-59962af5-f04c-4998-97bb-342aa7bf887f.png)
Notice the "inputPattern did not pass!" log.

Note: If you want to implement an input mask instead, check out this module:
https://hodgef.com/simple-keyboard/modules/input-mask/

Regards,
Francisco Hodge
