### ISSUE TITLE
I don't understand how to change the language.

### ISSUE THREAD

**Issue by silach93** [hodgef/react-simple-keyboard#2361]
I'm russian student and my english language proficiency level. But i ask for help, please. I don't understand how to change the language. I work for ReactJS. I hope for understanding. Thank you in advance.

**Comment by hodgef** [comment]
Hello @silach93,

Check out https://hodgef.com/simple-keyboard/modules/simple-keyboard-layouts/

Regards,
Francisco Hodge

**Comment by silach93** [comment]
Hellow Francisco Hodge,
The problem is that I do not know how to do it on ReactJS.

**Comment by hodgef** [comment]
It's essentially the same (you spread the `layout` into your component). Check out the demo in this post:
https://github.com/hodgef/react-simple-keyboard/issues/1839#issuecomment-1082567057

**Comment by silach93** [comment]
I apologize for my stupidity, but I use JSX code.


import React, { useRef, useState } from "react";
import ReactDOM from "react-dom";
import Keyboard from "react-simple-keyboard";

// Instead of the default import, you can also use this:
// import { KeyboardReact as Keyboard } from "react-simple-keyboard";

import "react-simple-keyboard/build/css/index.css";
import "./styles.css";

function App() {
  const [input, setInput] = useState("");
  const [layout, setLayout] = useState("default");
  const keyboard = useRef();

  const onChange = input => {
    setInput(input);
    console.log("Input changed", input);
  };

  const handleShift = () => {
    const newLayoutName = layout === "default" ? "shift" : "default";
    setLayout(newLayoutName);
  };

  const onKeyPress = button => {
    console.log("Button pressed", button);

    /**
     * If you want to handle the shift and caps lock buttons
     */
    if (button === "{shift}" || button === "{lock}") handleShift();
  };

  const onChangeInput = event => {
    const input = event.target.value;
    setInput(input);
    keyboard.current.setInput(input);
  };

  return (
    <div className="App">
      <input
        value={input}
        placeholder={"Tap on the virtual keyboard to start"}
        onChange={onChangeInput}
      />
      <Keyboard
        keyboardRef={r => (keyboard.current = r)}
        layoutName={layout}
        onChange={onChange}
        onKeyPress={onKeyPress}
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by hodgef** [comment]
Compare your code to this one, and change accordingly:
https://codesandbox.io/s/amazing-booth-x1vszm

You can't really go wrong there. Regards

**Comment by silach93** [comment]
Thank you very much and i am sorry for the time taken away google translate.
