### ISSUE TITLE
Infinite loop when debugging

### ISSUE THREAD

**Issue by ostin-r** [hodgef/react-simple-keyboard#2451]
Version 3.6.39

Everything works fine when running the following simple [example](https://hodgef.com/simple-keyboard/editor/?d=hodgef/react-simple-keyboard-demos/tree/master). When debugging with the same example, adding breakpoints to the onChange and onKeyPress functions begins an infinite loop that continuously re-renders and keeps submitting the same character.  The frames suggest the call is coming from an 'Async call from setTimeout'

For context I am running React 18.0.0 in Pycharm 2023.1.

I recognize this may be a deeper issue with my setup.  Any recommendations for further debugging are welcome.

**Comment by ostin-r** [comment]
Looks like this was an issue with using Google Chrome for debugging, as switching to Firefox did not produce the issue.

**Comment by hodgef** [comment]
I can also repro this. I will double check the logic to make sure it's a browser issue.

**Comment by hodgef** [comment]
Ok yeah, this is a browser issue. Chrome is not firing button nor document mouseup at all.

To work around this issue, I recommend using the `disableButtonHold` option as needed:
https://hodgef.com/simple-keyboard/documentation/options/disablebuttonhold/

Regards,
Francisco Hodge

**Comment by ostin-r** [comment]
Excellent, I appreciate you looking into this.
