### ISSUE TITLE
Highlighting a key pressed

### ISSUE THREAD

**Issue by sitaramshelke** [hodgef/react-simple-keyboard#246]
Hello, @hodgef Thank you for the keyboard! it works like a charm.
I have a question, is there a way to highlight when a screen keyboard key is pressed with some kind of animation or color change?

**Comment by hodgef** [comment]
Hey @sitaramshelke,

Thanks! I recommend using CSS for the visuals/animations. Here's a quick demo:

https://codesandbox.io/s/simple-keyboard-npm-demos-63vr6?fontsize=14&module=%2Fsrc%2Findex.css

Hope that helps!
Francisco Hodge
