### ISSUE TITLE
Can't get caret position right in react typescript project

### ISSUE THREAD

**Issue by Littlewiz123** [hodgef/react-simple-keyboard#2461]
react-simple-keyboard: "latest version"

https://codesandbox.io/s/react-simple-keyboard-typescript-demos-kj3r1?file=/src/KeyboardWrapper.tsx

I'm testing your example and currently using package in my personal project. But event time react set state for the new input value, the input component keep setting the caret position back to the end of line. 

Can someone help me with this case ?

**Comment by hodgef** [comment]
Hello @Littlewiz123,

I'm not sure what you mean. Could you provide a repro? I will be able to debug it when that is provided.

Thanks!
Francisco Hodge
