### ISSUE TITLE
input type="email" not working

### ISSUE THREAD

**Issue by vickylance** [hodgef/react-simple-keyboard#247]
**React-simple-keyboard version**
Using version 2.0.15

**Describe the bug**
Having input type as email and then using the keyboard to type some input and then manually changing the caret position in the input field then again typing in the virtual keyboard the text is appended to the end of the input field rather than the cursor position. But if I remove the input type for the input tag everything is working fine.

https://codesandbox.io/s/react-simple-keyboard-demo-rng8n

**Comment by hodgef** [comment]
Hello @vickylance,

I've encountered this issue before. Some input types do not support caret positioning (selectionStart). Therefore I would recommend always using text inputs.

More information:
https://html.spec.whatwg.org/multipage/input.html#do-not-apply

![image](https://user-images.githubusercontent.com/25509135/67106254-3cddc280-f198-11e9-8098-36f54c07e5a5.png)


There are other means to achieve input validation or to restrict entered input. Check out this docs entry for more info:
https://franciscohodge.com/projects/react-simple-keyboard/qa-use-cases/#input-validation

Regards,
Francisco Hodge
