### ISSUE TITLE
Missing keyboard destroy on unmount

### ISSUE THREAD

**Issue by TheMatrixan** [hodgef/react-simple-keyboard#2522]
**React-simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**
`Keyboard` from `simple-keyboard` has method: `destroy` to remove all event listeners. But you forgot to use it in `useEffect` return function in `KeyboardModern` and `Keyboard` components here:
- https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/KeyboardModern.tsx#L48
- and here https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/Keyboard.tsx#L46

That's why when you e.g. have this keyboard in modal and enable `physicalKeyboardHighlightPress`, after reopening the modal it will press letter twice. If you do it again, it will press it thrice and so on. 

Please add return function like this:

```tsx
useEffect(() => {
  const keyboard = new Keyboard( ... )
  return () => {
    keyboard.destroy();
  }
}, [])
```

**Comment by TheMatrixan** [comment]
Any updates? @hodgef

**Comment by hodgef** [comment]
Hey @TheMatrixan, do you mind sending in a PR for this? I can also take care of it, but I think a PR would be preferable. Thanks!

**Comment by GoannaGuy** [comment]
I just ran into this issue myself today. It appears that @TheMatrixan hasn't sent in a PR yet, so I provided one.

**Comment by hodgef** [comment]
The contribution by @GoannaGuy has been merged and a new version will be deployed in a few minutes. Thank you so much!
