### ISSUE TITLE
The .com key is not complying with maxLength because of === check in simple-keyboard

### ISSUE THREAD

**Issue by vickylance** [hodgef/react-simple-keyboard#256]
**React-simple-keyboard version**
Using the latest version

**Describe the bug**
Having the ".com" button clicked multiple times it does not take the maxLength property because for the triple equality check in simple-keyboard Utilities.js line 307. Once the ".com" crosses the maxLength it just keeps ongoing.

**Comment by hodgef** [comment]
Thanks for reporting this @vickylance, indeed it is a bug!

I've noticed your PR in the upstream project here:
https://github.com/hodgef/simple-keyboard/pull/285

I will merge this shortly, and the release will follow.

Thanks!

**Comment by vickylance** [comment]
@hodgef Thanks a lot for merging. You can close this ticket once the release is published
