### ISSUE TITLE
caret position

### ISSUE THREAD

**Issue by arianRotor** [hodgef/react-simple-keyboard#258]
I'm using react-simple-keyboard for multiple inputs, but when the user clicks somewhere in the middle of the input, the keyboard updates the  caret position and puts the first letter in correct place. However, it resets the caret position to null afterwards and puts the other added letters at the end. I didn't come across this issue with simple input and it only happens when I use multiple inputs.

**Comment by hodgef** [comment]
Hello @arianRotor ,

I can't seem to reproduce this ussue on the multiple inputs demo:
https://codesandbox.io/s/github/hodgef/react-simple-keyboard-demos/tree/uc-multiple-inputs/

Could you edit that demo as to show the issue, then share the link? Or if you can share a test repo or snippet, that'd be great.

Regards,
Francisco Hodge

**Comment by arianRotor** [comment]
thanks Francisco for the link, I updated the library to the latest version and it get fixed, I assume the issue is  in older veriosn ( 1.21.2 ). is there any way to fix the issue in older versions by Javascript without updating the library ?

**Comment by hodgef** [comment]
Hey @arianRotor,

Glad you got it fixed! I don't think I can backport fixes to older versions, but if you come across any other issues you can always reach out and I'll try to help!

Regards,
Francisco Hodge
