### ISSUE TITLE
No input on mobile scrolling

### ISSUE THREAD

**Issue by Tomo-Pavicic-Personal** [hodgef/react-simple-keyboard#2686]
When I use the keyboard for my mobile site, the keys are pressed if a user tries to scroll down the page with their finger on a key.

Ideally there would be an option to stop this behaviour. Not sure if this is possible but my other buttons use onClick and don't have this problem.

**Comment by hodgef** [comment]
Hello @Tomo-Pavicic-Personal,

You can try this option: [`useMouseEvents`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/).

Regards,
Francisco Hodge

**Comment by Tomo-Pavicic-Personal** [comment]
Worked perfectly,

Thank you @hodgef
