### ISSUE TITLE
Use react-icons for custom keys

### ISSUE THREAD

**Issue by Zerak630** [hodgef/react-simple-keyboard#2704]
> react: 18.2.0
> react-icons: 5.0.1
> react-simple-keyboard: 3.7.94

**Is your feature request related to a problem? Please describe.**
My target browser does not support some characters (like ⌫, ⏎ or ⇧). I need to find an other way to display them, or simply choosing something else.

**Describe the solution you'd like**
As we can use `<img>`, make it work for react-icons.

```
/* Write this */
'{shift}': `${<ImArrowUp/>}`

/* Or this */
'{shift}': `<ImArrowUp/>`

/* Or this */
'{shift}': <ImArrowUp/>
```

**Comment by hodgef** [comment]
Hello @Zerak630, please check out this answer for an explanation on why this is not supported: https://github.com/hodgef/react-simple-keyboard/issues/1204#issuecomment-841787672

If you really need to use components, you can use `renderToString` as shown here: https://github.com/hodgef/react-simple-keyboard/issues/1204#issuecomment-1882881124

Regards,
Francisco Hodge

**Comment by Zerak630** [comment]
I thought I had looked carefully at the existing issues before, but the fact is that I didn't! Thank you very much for your quick response.

Best regards
