### ISSUE TITLE
preventDownMouseDefault Caret Workaround on MUI TextField Makes Caret Jump To End of TextField

### ISSUE THREAD

**Issue by epicstar** [hodgef/react-simple-keyboard#2730]
**React-simple-keyboard version**
3.7.105

**Describe the bug**

When using trying to use the [`preventDownMouseDefault`](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/) argument with a [MUI TextField](https://mui.com/material-ui/react-text-field/), after focusing on the MUI TextField then clicking on a key on the keyboard, the cursor jumps to the end of the input field.

I expect the official #44 solution to work instead.

I do something like this:
1. `preventMouseDownDefault` is enabled on React-Simple-Keyboard
1. setting the a `ref` on MUI's `TextField`'s `inputRef` (using its `ref` also does not work as expected, but in a different way such that it's as if we never added the caret positioning code)
1. telling the `ref` to `setSelectionRange` on the caret position of the keyboard when the keyboard's input changes

**Screenshots**
No screenshot, but here's the [devbox of the problem](https://codesandbox.io/p/devbox/react-simple-keyboard-mui-mousepreventdefault-bug-y5mtst?embed=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluk9j4bk0008356kahmc2qtk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluk9j4bk0002356kjm4yi4aa%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluk9j4bk0005356kay3yri5t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluk9j4bk0007356kv2b11v00%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluk9j4bk0002356kjm4yi4aa%2522%253A%257B%2522id%2522%253A%2522cluk9j4bk0002356kjm4yi4aa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluk9ypcx0002356kyus4juc2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A43%252C%2522startColumn%2522%253A15%252C%2522endLineNumber%2522%253A43%252C%2522endColumn%2522%253A15%257D%255D%257D%255D%252C%2522activeTabId%2522%253A%2522cluk9ypcx0002356kyus4juc2%2522%257D%252C%2522cluk9j4bk0007356kv2b11v00%2522%253A%257B%2522id%2522%253A%2522cluk9j4bk0007356kv2b11v00%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522VIRTUAL_MACHINE%2522%252C%2522id%2522%253A%2522cluka7qgi009g356qvu7cugdw%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522clukaw992007f356kn3ttqbph%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clukaw992007f356kn3ttqbph%2522%257D%252C%2522cluk9j4bk0005356kay3yri5t%2522%253A%257B%2522id%2522%253A%2522cluk9j4bk0005356kay3yri5t%2522%252C%2522activeTabId%2522%253A%2522cluka72mn002h356qfcef7cqq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluk9j4bk0004356kgev11c2t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluk9h863008edjip3swbg8ax%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cluka72mn002h356qfcef7cqq%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by hodgef** [comment]
Hey @epicstar, I had a quick look and it seems your ref is not pointing to an `input` but to a `div`.

![image](https://github.com/hodgef/react-simple-keyboard/assets/25509135/96992a35-c061-44ee-b60b-177bed14bc7d)

I suggest you debug it further. I am not very familiar with the inner workings of MUI TextFields so I think their team can help more on that.

Thanks,
Francisco Hodge

**Comment by hodgef** [comment]
Here's a sample fix: https://codesandbox.io/p/devbox/react-simple-keyboard-mui-mousepreventdefault-bug-forked-5rypt6?file=%2Fsrc%2FApp.tsx%3A20%2C45

**Comment by epicstar** [comment]
Thank you. This should get me to a solution.

The sample fix breaks keyboard input, but I think I can work around it. Thank you very much!
