### ISSUE TITLE
Backspace issue with initial value, manual mask logic, and rendering condition triggered by html input's onFocus

### ISSUE THREAD

**Issue by pablobrodt** [hodgef/react-simple-keyboard#2776]
So, i know this is a very specific issue, you can say just by the title.

In preparation for this cenario we should have:
- A logic to show/hide the keyboard (a simple state "showKeyboard" that is a boolean).
- An initial value being set by `onInit` prop callback or even with the ref.
- A function to show the value masked on the html input.

So lets describe when this issue happens:
You have your html input on screen and the keyboard is not rendered yet, because we only want the keyboard to be shown when the input gets focus.

You have a initial value to fill your html input and the Keyboard internal input. 

This value is not masked at all, we only apply a mask before we pass the value to the html input's value attribute.

So, when the html input triggers its onFocus callback, we set the boolean state that defines if the Keyboard is shown as true, then our Keyboard gets rendered and we set its input value with our intended initial value using the `onInit` prop and doing a `keyboard.setInput(initialValue)`.

After that, we want to edit the value, and try to erase it with backspace, but nothing happens.

A few observations:
- If we do exaclty tha same thing, but instead of onFocus we use onClick, it works.
- If we trigger the input focus using a html `<label>`, it works.
- If we just use a button to change the state and then render the keyboard, it works.

I couldn't find any relationship between the html input's onFocus and the Keyboard directly to make sense that the backspace dont work.

Here is a codesandbox with a repro example:
https://codesandbox.io/p/sandbox/react-simple-keyboard-backspace-focus-issue-7fp289

I'm using react-simple-keyboard 3.7.80

**Comment by hodgef** [comment]
Hello @pablobrodt,

When you click on the input, its [caret position is relayed to simple-keyboard](https://github.com/hodgef/simple-keyboard/blob/b45ea000279225ad2b82fddc2cc681b1443442ec/src/lib/components/Keyboard.ts#L1250). But in your case there's a mismatch between the string length in the input element and in the internal simple-keyboard state.

<img width="259" alt="image" src="https://github.com/hodgef/react-simple-keyboard/assets/25509135/bd53f6fd-c52e-49cf-987d-1623aeffcef1">

So as a result simple-keyboard tries to delete at a position that does not exist.

To fix this, you can use the option [`disableCaretPositioning`](https://hodgef.com/simple-keyboard/documentation/options/disablecaretpositioning/).

https://codesandbox.io/p/sandbox/react-simple-keyboard-backspace-focus-issue-forked-vhz9jx?file=%2Fsrc%2Fcomponents%2Fmy-keyboard%2Fmy-keyboard.component.tsx%3A46%2C7

Regards,
Francisco Hodge

**Comment by pablobrodt** [comment]
Hi @hodgef, the formatted string is only used for presentation reasons, when manipulating the input's value i'm using the raw value, so i couldn't understand why the keyboard is using the formatted value for the caret positioning.

Can you explain why?

**Comment by hodgef** [comment]
I linked to this part of the code above: https://github.com/hodgef/simple-keyboard/blob/b45ea000279225ad2b82fddc2cc681b1443442ec/src/lib/components/Keyboard.ts#L1250

When you click on an input, the **caret/cursor position** of your input is communicated to simple keyboard. If your masked input has its cursor at 20 and the internal (non-masked) input of simple-keyboard has a length of 16, then for sure backspace won't work when trying to remove a character at position 20.

You can have a look at the console in my example to verify. Thanks!

**Comment by pablobrodt** [comment]
Yeah thats exactly what i wanted to understand, thank you very much.
