### ISSUE TITLE
Problem with phisicalKeyboardHighlight

### ISSUE THREAD

**Issue by sensureStefano** [hodgef/react-simple-keyboard#2779]
**React-simple-keyboard version**
"^3.7.15"

**Describe the bug**
I have a react component that renders the keyboard with these specs:
```javascript
<KeyboardReact
      keyboardRef={(r) => (keyboard.current = r)}
      layoutName={layout}
      onKeyPress={onKeyPress}
      layout={layoutType[langInternal] ? layoutType[langInternal] : layoutType["ENG"]}
      display={customDisplay}
      mergeDisplay={true}
      useButtonTag={true}
      //inputPattern={mode=="numeric"?/[+-]?(\d*\.\d+|\d*\.|\d+\.\d*|\d+)/gm: mode=="text"&&maxLength?/^[\w\W]{0,3}$/:null}
      theme={`hg-theme-default hg-layout-default ${theme == "dark" ? "myTheme_dark" : "myTheme_light"}`}
      physicalKeyboardHighlight={true}
      syncInstanceInputs={true}
    />
``` 
I would like to make sure that if the variable passed to the component called psw is true, then the keys do not light up if I use the physical keyboard. if I put the variable like this:
```javascript
physicalKeyboardHighlight={psw ? false : true}
``` 
It doesn't work and stays lit when I physically press the keys.
How can I do? is it a bug?

**Comment by hodgef** [comment]
Hello @sensureStefano,

This seems to work for me:
https://codesandbox.io/p/sandbox/fervent-dirac-v247gd?file=%2Fsrc%2Findex.js%3A69%2C18

If it still doesn't work on your end, try setting `debug={true}`

Regards,
Francisco Hodge

**Comment by sensureStefano** [comment]
> Hello @sensureStefano,
> 
> This seems to work for me: https://codesandbox.io/p/sandbox/fervent-dirac-v247gd?file=%2Fsrc%2Findex.js%3A69%2C18
> 
> If it still doesn't work on your end, try setting `debug={true}`. Or please provide a sandbox/test git repo to help with debugging.
> 
> Thanks, Francisco Hodge

Hi, sadly the codesandobox is missing in my screen. it return 404 not found...

**Comment by hodgef** [comment]
Wow you are right, [Here's the updated link](https://codesandbox.io/p/sandbox/fervent-dirac-v247gd). Thanks

**Comment by sensureStefano** [comment]
Ok... i try to do a sandbox too but in the sandbox works, in the code in my system is not working.... idk
