### ISSUE TITLE
Caret position with 'touchmove'

### ISSUE THREAD

**Issue by Reibnitz** [hodgef/react-simple-keyboard#2810]
**Is your feature request related to a problem? Please describe.**
When repositioning the caret on a touch screen with the 'touchmove' event (tap over the word, hold and drag your finger to reposition the caret), the keyboard doesn't recognize the final position and writes from the initially tapped position, even though the caret in the input is shown in a different place.

**Describe the solution you'd like**
After some tinkering around, I found a solution for it. I'd like to see a guideline on the documentation for dealing with this issue so others don't have to spend as much time as I did. Here's my solution, but feel free to change it as you see fit: https://stackblitz.com/edit/github-jojtpe-8j2thu?file=src%2Findex.js

**Describe alternatives you've considered**
I tried attaching event listeners to 'touchmove' and 'touchend' events, but that doesn't help, as this functionality comes from the browser and it doesn't trigger any events we can listen to. Another alternative would be to preventDefault on the 'touchmove' event in the input, but that would require rewriting the caret repositioning functionality from scratch.

**Comment by hodgef** [comment]
Hello @Reibnitz,

I believe this issue might be the same one brought up in https://github.com/hodgef/simple-keyboard/pull/2277 and others.

Do you mind providing more info such as browser and OS, and describe your solution? There's already a `selectionchange` event in the codebase, but the handler does not apply to Firefox as this browser doesn't always report the correct caret position.

https://github.com/hodgef/simple-keyboard/blob/1efd9aa837fdf96d0d7dd9b7ef28fc3c67dc3b8a/src/lib/components/Keyboard.ts#L1154
https://github.com/hodgef/simple-keyboard/blob/1efd9aa837fdf96d0d7dd9b7ef28fc3c67dc3b8a/src/lib/components/Keyboard.ts#L1214

I'll reopen when I get a bit more actionable information. I could always add something to the Q&A section in the docs but people might find that page through Google search... and the existing GitHub issues are likely to rank higher.

Thanks,
Francisco Hodge

**Comment by Reibnitz** [comment]
Hey, @hodgef 
First of all, thanks for the quick answer and all the effort behind creating and maintaining this package.

The OS is Windows 10 Enterprise 2016 LTSB, and the browser is Chrome 126.0.6478.127. This is running in a touch panel.

The solution involves adding an eventListener for the 'selectionchange' event, which sets the keyboard's caret position to the input's selectionStart value. Additionally, it also sets the input's selectionStart to the keyboard's caret position on the onChange method of the keyboard.

With these two operations combined, the keyboard is able to support the caret repositioning functionality that the browser provides for 'touchmove' events.

At least on Chrome, this 'touchmove' is "hijacked" by the browser, so it does its own functionality and doesn't propagate the touch events further. Since it doesn't propagate 'touchend', the keyboard can't listen to it and place the caret accordingly, so the caret position in the input (the one we see) is not the same as the Keyboard component's.

You can reproduce this on your mobile by:

1. Open https://hodgef.com/simple-keyboard/demos/
2. Type some random letters
3. Tap over the written text in the input area
4. Tap again and hold, moving your finger to replace the caret
5. Add another random letter to it
6. You'll see that the new letter is added to the position you originally tapped, and not to the position you dragged the caret to
7. Now do the same on https://stackblitz.com/edit/github-jojtpe-8j2thu?file=src%2Findex.js

Once again, thank you
Lucas

**Comment by hodgef** [comment]
Thank you for the useful details @Reibnitz, I will add an entry to the Q&A section soon linking to this.

**Comment by hodgef** [comment]
Will close this one, but please rest assured I am tracking this internally. Thanks
