### ISSUE TITLE
useMouseEvents not working

### ISSUE THREAD

**Issue by adventmedia** [hodgef/react-simple-keyboard#2936]
version: 3.8.20
Microsoft Edge 130.0.2849.80 on MacOS 15.1

**Describe the bug**
with `useMouseEvents={true}`, onKeyPress is still returning pointer events:

`const onKeyPress = (button: string, evt?: MouseEvent) => {
  console.log(‘onKeyPress’, button, evt);

**Screenshots**
the console.log
![screenshot_1344](https://github.com/user-attachments/assets/de78baa0-98b0-4242-b4ce-fcf031ca99d8)

Or do I misunderstand what `useMouseEvents` does?

**Comment by hodgef** [comment]
Hello @adventmedia,

Your understanding is correct. It appears that the browsers return PointerEvents out of the `onclick`.

![image](https://github.com/user-attachments/assets/9d7fed8e-eef7-4681-80cb-5fb649018ac4)

But still return MouseEvent when using `onmousedown`

![image](https://github.com/user-attachments/assets/8763e9c5-afb4-4539-a635-37490c2cecc4)

Will have a look later on how to fix this without introducing a breaking change. Thanks

**Comment by hodgef** [comment]
In the latest version, you can use the following options together:

```js
useMouseEvents: true,
clickOnMouseDown: true
```

and you'll see only MouseEvents in your onKeyPress. This is because the `onmousedown` will be used instead of the `onclick` (for key presses).

Thanks,
Francisco Hodge
