### ISSUE TITLE
keyboard setInput is not working

### ISSUE THREAD

**Issue by WajidAfridi48** [hodgef/react-simple-keyboard#299]
I am using this in my project, when i click on input, my app crached with follow message.
```Uncaught TypeError: Cannot read property 'setInput' of undefined.```

**Comment by hodgef** [comment]
Hello @WajidAfridi48,

Have you updated from version 1 to 2? If so, there's a breaking change described here:
https://github.com/hodgef/react-simple-keyboard/releases/tag/2.0.0

Just make sure to follow the instructions in that link to upgrade. You can also check out the react demos throughout the [documentation](https://simple-keyboard.com/react/documentation). They've all been updated.

Regards,
Francisco Hodge
