### ISSUE TITLE
Multiple Language for backspace button

### ISSUE THREAD

**Issue by amalheiros** [hodgef/react-simple-keyboard#307]
It will be awesome if you can set as parameter the language for all buttons, including the bksp property.

I already saw for the other buttons, but I didn't saw anything for this property.

Tks!

**Comment by hodgef** [comment]
Hello @amalheiros,

`{bksp}` is a button that has [a preset function in the code](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/Utilities.js#L135), so this is why it has remained the same in all layouts (including language layouts).


I agree that it should be translatable also. One way to translate this button is to use the `display` property like this:

```
"display" : {
  "{bksp}" : "Retrocesso"
},
mergeDisplay: true
```
https://simple-keyboard.com/documentation/#display

Regards,
Francisco Hodge
