### ISSUE TITLE
clearInput upon click of a button

### ISSUE THREAD

**Issue by exylzior** [hodgef/react-simple-keyboard#33]
I'm trying to implement clear Input when button is press the input text doesn't get clear. When I press another button to what happens the previous text gets cleared and replace by the text that I have press.

**Comment by exylzior** [comment]
Just for clarification the `this.setState({"input:"})` for the reset of state and `this.keyboard.clearInput` for reset of the keyboard. Right now I'm trying to implement it in a

```
form.setFieldsValue({
   pin: this.state.input
})
```
I was able to change the state of the input but when I try doing the clear it goes back to that previous use case that I encountered it. Now I'm trying to do the specific input but I don't have an example to follow through. Maybe you can give an example.

Thank you for the response ! ! !

**Comment by hodgef** [comment]
Hey @exylzior, it seems you're using this with an input plugin?

Could you edit (this sandbox)[https://codesandbox.io/s/q8z4j6q6p6], adapt it to your current use-case, then send me the link? That will be a lot easier to debug!

I'll reopen the ticket once I have that example :)

Regards

**Comment by exylzior** [comment]
Hi @hodgef 

I was able to figure out using my input plugin. Right now I'm encountering an issue if there are 2 Keyboard displays. See [this sandbox](https://codesandbox.io/s/4jy6z55904). I tried making the functions identical but the first keyboard behaves differently.

Thank you for the quick response ! ! !

**Comment by hodgef** [comment]
Hello @exylzior,

Thanks for following-up, this is an use-case I hadn't tested before (I had tested for [one keyboard for multiple inputs](https://franciscohodge.com/projects/react-simple-keyboard/qa-use-cases/#using-several-inputs)). So trying out your sandbox helped me uncover a bug in `clearInput` and another unrelated issue.

Those are fixed as of 1.12.0, so I'd suggest an `npm iinstall react-simple-keyboard@latest --save`

Here's an updated sandbox which I believe will work for your use-case:
https://codesandbox.io/s/8x5j4xror8

I will update the docs with this use-case soon. If you still have issues, let me know and we'll look at this further.

Regards,
Francisco Hodge
