### ISSUE TITLE
Backspace not working with several input method

### ISSUE THREAD

**Issue by NSLog0** [hodgef/react-simple-keyboard#35]
**React-simple-keyboard version**
I'm using react-simple-keyboard ->  1.14.1 and I've following this [link](https://franciscohodge.com/projects/react-simple-keyboard/qa-use-cases/#using-several-inputs) to handle multiple inputs. Everything works fine unless backspace button doesn't return any response from `onChange` function

For now, I must click on an input again then backspace will be working.

any help or suggestion?

**Screenshots**

<img width="1041" alt="screen shot 2562-01-01 at 16 16 50" src="https://user-images.githubusercontent.com/1640817/50571606-40f34c00-0de1-11e9-90aa-ba31e2978b3c.png">

**Comment by hodgef** [comment]
Hello @NSLog0,

I've tweaked a bit the demo and added it to a sandbox.

Here's the link:
https://codesandbox.io/s/github/hodgef/react-simple-keyboard-demos/tree/uc-multiple-inputs/

If that sandbox doesn't fix your issue, please let me know and I'll reopen the ticket. I will need to reproduce the issue so if you share a [new sandbox](https://codesandbox.io) with the issue it will help a lot.

Regards,
Francisco Hodge

**Comment by NSLog0** [comment]
Hello @hodgef , 
Thank you for support. I can't fix the problem and I create a sandbox https://codesandbox.io/s/7kz33ylkj1 , Could you please check it

The project structure, I split all the file and use `import` to compose it like my local project

**Comment by hodgef** [comment]
Hey @NSLog0, your example seems to be missing a few things from the sandbox I shared.

Basically, you need to set the `inputName` option in simple-keyboard and call `setInput` on input change.

Also, it seems you are destroying the keyboard instance every time you set `this.state.keyboardOn`. This also destroys the internal keyboard input. I think you should rather hide the keyboard through CSS.

Here's a modified sandbox, hope it helps. 
https://codesandbox.io/s/kkn757p1nv

As usual, let me know if you have issues and I'll reopen the thread

Francisco Hodge

**Comment by hodgef** [comment]
Hello @NSLog0,

Sorry about that, I have to delete the examples after some time as codesandbox just lets me host 50.
Here's a new example, feel free to fork/copy it : 

https://codesandbox.io/s/3xvm7owmvm
Regards

**Comment by NSLog0** [comment]
I've downloaded to my machine. So you can delete it

Thank you.

**Comment by NSLog0** [comment]
Can you check at this https://codesandbox.io/s/o5w74o12qz

I used your code to create this one but seems it cannot delete a value

**Comment by NSLog0** [comment]
I think I've found the problem. it's because of `value={get(this.state, "oximiter", "N/A")}`. Once I defined the state ` oximiter: undefined` then `get` function return `N/A` to input then it made something broken

**Comment by hodgef** [comment]
@NSLog0 Is there still an issue? Your sandbox seems to work fine for me

**Comment by NSLog0** [comment]
I think I just found something on this statement `get(this.state, "pb", "N/A")` since I initiated state to `undefined` and `get(this.state, "pb", "N/A")` will be put `N/A` to input which not set by keyboard. Maybe this is a cause of the problem. I tried to set state to empty string it seems to work fine

**Comment by hodgef** [comment]
@NSLog0 I see - If you want to have a default value, check out what I did on that sandbox inside `componentDidMount`. Basically you have to call `setInput` so simple-keyboard's internal input is updated.

More details here: https://simple-keyboard.com/react/documentation/#setInput

Regards

**Comment by hodgef** [comment]
Hello @NSLog0,

I think the sandbox will solve your issues :)

https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-issues-35-1/tree/master/

Please refer to [the documentation](https://franciscohodge.com/projects/react-simple-keyboard/documentation) for more info.

(By the way, now I'm just saving all sandboxes to github, so rest assured the example won't be deleted)

Regards,
Francisco Hodge
