### ISSUE TITLE
React Virtual keyboard is not working with input mask also backspace is not working.

### ISSUE THREAD

**Issue by rajdoshi9089** [hodgef/react-simple-keyboard#36]
React Virtual keyboard is not working with input mask also backspace is not working.

**Comment by rajdoshi9089** [comment]
For Example i want to use DOB input mask but backspace is not working.

**Comment by hodgef** [comment]
Hello @rajdoshi9089,

simple-keyboard doesn't work out of the box with masking plugins. The following issue has more details:
https://github.com/hodgef/react-simple-keyboard/issues/7

I made a [masking module for simple-keyboard](https://github.com/hodgef/simple-keyboard-input-mask) to try and solve this, but it's at the alpha/experimental stage. You can try it out here:
https://codesandbox.io/s/xp895w7kpp

If this doesn't solve your issue, please reply with more details and a [sandbox](https://codesandbox.io) so I can better reproduce the issue.

Regards

**Comment by rajdoshi9089** [comment]
I need set conditional disableCaretPositioning based on true and false for handling multiple text box But it is not working

**Comment by nikita-reshetnyak** [comment]
I want to change mask and regex that i need but don't work
