### ISSUE TITLE
Insert input according to mouse position

### ISSUE THREAD

**Issue by chenDiDi** [hodgef/react-simple-keyboard#4]
can‘t Insert input according to mouse position；
cant support cross-line button display？

**Comment by hodgef** [comment]
Hello @chenDiDi,

This is currently not supported by simple-keyboard. The text is only appended for the moment.

I have this however as a To Do on the roadmap (second item):
https://github.com/hodgef/simple-keyboard/wiki/Roadmap

I hope I can release this soon enough, although I cannot provide a time estimate.

Sorry for the inconvenience,
Francisco Hodge

**Comment by hodgef** [comment]
Update: This is now supported!
