### ISSUE TITLE
Numeric theme

### ISSUE THREAD

**Issue by sgoudelis** [hodgef/react-simple-keyboard#40]
Not sure if this is a bug or me not using this properly. Through the react interface the theme option does not work. I am trying to setup to use the numeric keypad but I cant get this to work.

Usage:
```
                            <Keyboard
                                ref={r => (this.keyboard = r)}
                                layoutName={this.state.layoutName}
                                onChange={input => this.onChange(input)}
                                onKeyPress={button => this.onKeyPress(button)}
                                theme={"hg-theme-default hg-layout-numeric numeric-theme"}
                            />
```

Does anyone know how to use this feature ?

**Comment by hodgef** [comment]
Hello @sgoudelis,

I think you're missing the `layout` option.
Check out this demo (for `simple-keyboard`, but the options are the same)
https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/numeric-theme/

```
layout={{
    default: ["1 2 3", "4 5 6", "7 8 9", "{shift} 0 _", "{bksp}"],
    shift: ["! / #", "$ % ^", "& * (", "{shift} ) +", "{bksp}"]
}}
```

Hope that helps, if not let me know and we'll debug further.

Regards,
Francisco Hodge
