### ISSUE TITLE
math-based keyboard with mathjax question/bug

### ISSUE THREAD

**Issue by ggunti** [hodgef/react-simple-keyboard#41]
Hello!
I started to make a custom keyboard with math symbols using this library.
As you can see in the first screenshot, I have a button loaded with an integral symbol inside it. I loaded this symbol using mathjax, and I used the 'display' property of the Keyboard component to render the symbol inside the button. Everything is fine, until I click inside the editor box (actually I focus it). When I click inside it, I lose the integral symbol inside the Keyboard button, it is not visible anymore (as you can see in the second screenshot).

Screenshot 1:
![one](https://user-images.githubusercontent.com/26307699/54090141-b0edf780-4379-11e9-9ae5-b32cc6c54a69.png)

Screenshot 2:
![two](https://user-images.githubusercontent.com/26307699/54090144-b8ad9c00-4379-11e9-8a70-15831d6a7db5.png)

<b>So my question is:</b>
Why it is happening and how could I prevent it? I just want to keep the integral symbol visible all the time. I attach here all the code I wrote. Thanks in advance! :)

Code screenshot 1 (the main component "Start.js"):
![Start](https://user-images.githubusercontent.com/26307699/54090211-5739fd00-437a-11e9-9d42-3adec4230dae.png)

Code screenshot 2 (the logic - not finshed "ProblemEditor.page.js"):
![ProblemEditorPage](https://user-images.githubusercontent.com/26307699/54090220-7c2e7000-437a-11e9-976a-4eb85357eaeb.png)

Code screenshot 3 (the component "ProblemEditor.component.js"):
![ProblemEditor](https://user-images.githubusercontent.com/26307699/54090223-86e90500-437a-11e9-935b-641756a20d9e.png)

Code screenshot 4 (the css file "ProblemEditor.css"):
![ProblemEditorCss](https://user-images.githubusercontent.com/26307699/54090228-910b0380-437a-11e9-9ff4-eb401c8878b8.png)

**Comment by hodgef** [comment]
Hello @ggunti,

My guess is that there's a re-render going on somehow, but I'm not sure. If you could edit the following sandbox as to show the issue, that would really help me debug this:

https://codesandbox.io/s/github/hodgef/react-simple-keyboard-demos/tree/master/

I'll reopen the ticket once you provide that edited sandbox link.

Regards,
Francisco Hodge

**Comment by ggunti** [comment]
Alright, here it is: https://codesandbox.io/s/4z29xj5yx9
And the direct link to the running app: https://4z29xj5yx9.codesandbox.io/

**Comment by ggunti** [comment]
I think that the problem could be that the 'integral' property of 'display' object is a string. We can't pass react components directly to Keyboard buttons somehow (instead strings)?

**Comment by hodgef** [comment]
The display property basically injects HTML on the `span` of a `.hg-button`:
https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.js#L1098

I wish to keep it that way, to keep the behavior consistent across libraries (React, Angular, etc).

To provide more context: Initially the scope of the "display" property was to make "function buttons" (like `{bksp}`) display with a more friendly name such as `Backspace`.

https://simple-keyboard.com/documentation/#display

Perhaps `display` isn't the best way to accomplish your use-case. I'm currently trying something out in your sandbox, perhaps I'll find an alternative way to get it working.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @ggunti,

As suspected, clicking in and out of that input is triggering a re-render of the view. Then there seems to be an issue getting the formula to display correctly after this re-render, which I would attribute to the formula library (as simple-keyboard is simply taking the html input and doing an innerHTML).

I didn't want to come back empty handed though - so I tried to fix the sandbox for you but the end result was more of a hack.

Feel free to take this approach and turn it into something that works for you.
https://codesandbox.io/s/340o6nn2om

Regards,
Francisco Hodge

**Comment by ggunti** [comment]
Thank you @hodgef , but this is what I get:
![image](https://user-images.githubusercontent.com/26307699/54106705-abc39380-43df-11e9-9b30-771805055355.png)

**Comment by ggunti** [comment]
I think I found an acceptable solution which work without any problems. I share it here, it could be helpful for other users.

So:
1. I generate all the math symbols I need inside Keyboard buttons into .svg format (I use https://viereck.ch/latex-to-svg/ for generating svg from math symbols/equations). For example, I need an integral symbol inside the first button. Then I will have an integral.svg file which contain the integral in .svg format.
2. I include the svg files in my project and then use them in order to pass the symbols to the 'display' property of the Keyboard, like in the following image:
![image](https://user-images.githubusercontent.com/26307699/54120011-5bf4c480-43ff-11e9-940d-13bd47111084.png)

The result is amazing, the symbols are perfectly rendered inside the keyboard and they do not disappear if I click anywhere:
![image](https://user-images.githubusercontent.com/26307699/54120293-08cf4180-4400-11e9-9eef-7d57f15e8cb0.png)


This approach is enough good for me.

@hodgef  thank you for your help!

**Comment by hodgef** [comment]
Glad that you got it solved - Thanks for sharing your solution!
