### ISSUE TITLE
Ask for advice

### ISSUE THREAD

**Issue by gd-ldj** [hodgef/react-simple-keyboard#42]
It supports China's Pinyin input method ？

How can I use it to implement Chinese Pinyin input method ?

Thank you ！

**Comment by hodgef** [comment]
Hello @gd-ldj,

An out of the box implementation with Chinese layout can be found here (example in vanilla JS):
https://simple-keyboard.com/demo/#language-chinese

If this isn't what you're looking for, you can always customize your keyboard layout by passing the [`layout` option](https://simple-keyboard.com/react/documentation/#layout).

For example:
```
layout={{
  'default': [
    '` 1 2 3 4 5 6 7 8 9 0 - = {bksp}',
    '{tab} q w e r t y u i o p [ ] \\',
    '{lock} a s d f g h j k l ; \' {enter}',
    '{shift} z x c v b n m , . / {shift}',
    '.com @ {space}'
  ],
  'shift': [
    '~ ! @ # $ % ^ & * ( ) _ + {bksp}',
    '{tab} Q W E R T Y U I O P { } |',
    '{lock} A S D F G H J K L : " {enter}',
    '{shift} Z X C V B N M < > ? {shift}',
    '.com @ {space}'
  ]
}}
```

Regards,
Francisco Hodge

**Comment by gd-ldj** [comment]
Thank you, but it is an input method for Chinese, and what I want is another input method for Chinese, which is the Pinyin input method. I didn't find it, I have to develop it myself.

**Comment by hodgef** [comment]
Hello @gd-ldj,

I understand, sorry for not having this available! If you do develop this layout and wish to share it, feel free to post it here so I can merge it to [simple-keyboard-layouts](https://github.com/hodgef/simple-keyboard-layouts) with credit to you :)

Thanks!
Francisco Hodge

**Comment by gd-ldj** [comment]
Thanks，After I developed it，I am happy to share it
