### ISSUE TITLE
Gatsby (and similar static site generators) fail on build; package uses `window`, which doesn't work with SSR

### ISSUE THREAD

**Issue by j0hnm4r5** [hodgef/react-simple-keyboard#43]
**React-simple-keyboard version**
1.21.2

**Describe the bug**
When using a static site builder like Gatsby or Next.js, building a project with react-simple-keyboard fails, because `window` is used somewhere in the code.

**Comment by j0hnm4r5** [comment]
Looks like there is a workaround by following the instructions [here](https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-code-classlanguage-textwindowcode-is-defined) (at least for Gatsby).

**Comment by hodgef** [comment]
Hello @j0hnm4r5,

Thanks for the heads up! I should be able to take a look at this sometime tomorrow.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @j0hnm4r5,

After investigating this further, I would recommend using the core simple-keyboard library as well as dynamic imports for this use-case.

Here's a sandbox:
https://codesandbox.io/s/github/simple-keyboard/simple-keyboard-gatsby-demo/tree/master/

I will add it to the documentation shortly in case someone has the same issue.

Regards,
Francisco Hodge
