### ISSUE TITLE
Option to display Icons in Backspace and Other Keys

### ISSUE THREAD

**Issue by CPC-Dison** [hodgef/react-simple-keyboard#441]
Is there a way to make the backspace (and shift, caps lock etc.) keys render as icons or symbols, .e.g.,

http://blog.elliottcable.name/posts/useful_unicode.xhtml

The language translations are not optimal with English text. (backspace, shift, etc.)

**Comment by hodgef** [comment]
Hello @CPC-Dison, you can use the `display` property for that, e.g:

```
display={{
  '{bksp}': '⌫',
  ...
}}
mergeDisplay
```
https://simple-keyboard.com/react/documentation/#display

I agree that the translations are not optimal. It's a current design limitation as `simple-keyboard-layouts` targets the `layout` option. Ideally it should output translations for special keys (`display` option) too.. 

I added this as a to-do here: https://github.com/hodgef/simple-keyboard/projects/3#card-33645905

Regards,
Francisco Hodge
