### ISSUE TITLE
input doesn't "scroll" when content overflows width or height

### ISSUE THREAD

**Issue by a40637francisco** [hodgef/react-simple-keyboard#45]
I'm running the lastest version, 1.21.3

If you press the keys until the input is filled to its width, the input does not scroll to see the most recent value and the end of the value

example:
|               | <- input size
|abcdefge|ijklmnop <- when it overflows 

The visible values are always the same, it never scrolls to the most recent.

This happens in the Demos too, with a textarea if you press Enter a couple of times till it "overflows" you won't be able to see what you are typing unless you use the scroll bar to scroll down.

**Comment by hodgef** [comment]
Hello @a40637francisco,

Unfortunately, I don't think this is a simple-keyboard bug. Simple-keyboard doesn't handle input elements (it has an internal input value). Moreover, the demos are just brief examples to get you started.  They're not meant to cover all cases, so developers will need to adapt/improve them to their needs.

I think the question here is essentially: _"Why doesn't my input scroll to the left, after I set its value with Javascript"_, which is a general Javascript question. Here's a few SO posts discussing it:

1. [“scroll” to the end of the input after js modifies input's value.](https://stackoverflow.com/questions/14358462/scroll-to-the-end-of-the-input-after-js-modifies-inputs-value)
2. [“Scroll” to the very right of a long text input.](https://stackoverflow.com/questions/1962168/scroll-to-the-very-right-of-a-long-text-input)


Based on these StackOverflow posts and [an example from the docs](https://franciscohodge.com/projects/react-simple-keyboard/documentation/#preventMouseDownDefault) I came up with this:

https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-uc-45-scroll-input-overflow-preventMouseDownDefault/tree/master/

Of course, this sandbox example won't cover all cases. It's meant as an example that you could then adapt/improve as needed.

Regards,
Francisco Hodge
