### ISSUE TITLE
Pass reference of an input variable through options

### ISSUE THREAD

**Issue by lukavuletic** [hodgef/react-simple-keyboard#457]
My suggestion is to make one able to pass value through options which will be changed internally with setInput(). 

Problem I have encountered with this is if one is using a component and wants to implement custom logic with onKeyPress button, all the logic has to be implemented through keyboardRef and then written on the actual onKeyPress prop. Other way is to pass a ref to the store if one would call onKeyPress from the store, but that solution is also not clear.

So why not make a prop called value which will be a reference to some variable that can then be changed from both the library and the store?

**Comment by hodgef** [comment]
Hello @lukavuletic,

I understand your concerns. My goal is to keep react-simple-keyboard and the vanilla js version simple-keyboard 1:1 to make it easier to maintain.

Right now react-simple-keyboard is just a wrapper, which is quite handy and keeps the functionality consistent. It also spares me from having to write even more docs :)

Also, having simple-keyboard mutate a value it is passed through props is not ideal. The getter (getInput) / setter (setInput) and callback (onChange) approaches are safer in my opinion. By using an internal input buffer, I can avoid implementation bugs in caret positioning, etc. Less headaches down the road.

For these reasons I think it's best to leave this as-is. However simple-keyboard is flexible. Feel free to create a [module](https://franciscohodge.com/projects/simple-keyboard/modules/) that does your changes or just wrap simple-keyboard in a [wrapper](https://franciscohodge.com/projects/react-simple-keyboard/demos/typescript-hooks-demo/) and then do these changes inside the wrapper.

Regards,
Francisco Hodge
