### ISSUE TITLE
How to get mobile keyboard

### ISSUE THREAD

**Issue by laclance** [hodgef/react-simple-keyboard#463]
There is a demo for a mobile keyboard https://franciscohodge.com/projects/simple-keyboard/demo-showcase/mobile/.
But I dont see how to implement this?

**Comment by hodgef** [comment]
Hello @laclance,

Under the demos there are examples. You can open them to see the code:

![image](https://user-images.githubusercontent.com/25509135/76861016-4dbb5e80-6832-11ea-9cfa-83b1e8f6061d.png)

Note: Some demos only have JS examples, which you would need to adapt if you're using a framework or library.

Regards,
Francisco Hodge

**Comment by laclance** [comment]
The code for the demos does not show
![Screenshot (23)](https://user-images.githubusercontent.com/10835285/76873939-1fac3d80-6877-11ea-9419-6e395d5c2392.png)

**Comment by hodgef** [comment]
It seems there's an issue with codesandbox again:

![image](https://user-images.githubusercontent.com/25509135/76874424-8f093980-6845-11ea-83ab-8fba5567f2bd.png)
https://github.com/tannerlinsley/react-table/issues/1968

Unfortunately the only alternative I have is to link you to the demo's repo:
https://github.com/simple-keyboard/simple-keyboard-npm-demos/tree/mobile

I'll look into getting rid of codesandbox along with re-factoring the docs.

Regards,
Francisco Hodge

**Comment by laclance** [comment]
ok thank you very much.
