### ISSUE TITLE
After setting prevent Mouse Default=true, long press and move away, the input value will appear all the time.

### ISSUE THREAD

**Issue by gd-ldj** [hodgef/react-simple-keyboard#47]
**React-simple-keyboard version**

"react-simple-keyboard": "1.21.6",

**Describe the bug**

When I set preventMouseDefault=true, press a key on the keyboard for a while, move it out of the keyboard area, then release it, it will appear all the time.
![image](https://images.gitee.com/uploads/images/2019/0417/171824_9d381aaf_2664276.gif)

**Comment by hodgef** [comment]
Hello @gd-ldj,

Thank you for reporting this issue. It should be fixed shortly.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hey @gd-ldj,

The issue should now be fixed. Feel free to update to react-simple-keyboard@1.21.7.

Regards,
Francisco Hodge

**Comment by gd-ldj** [comment]
Thank you. It's ok.
