### ISSUE TITLE
Backspace always deletes last character

### ISSUE THREAD

**Issue by chhunchha** [hodgef/react-simple-keyboard#5]
Backspace key is always deleting last character. 
Steps to reproduce:

'|' is showing cursor position

1. Type few characters for example - "REACT|"
2. move cursor in between some where - for example - "REA|CT"
3. Press backspace - it deletes 'T' rather than 'A'

**Comment by chhunchha** [comment]
Looks like I should raise this issue for simple-keyboard

**Comment by chhunchha** [comment]
Looks like issue is in simple-keyboard. Opened one there too.

**Comment by hodgef** [comment]
Hello @chhunchha,

Currently text is appended only. However, adding text from the cursor is on the Roadmap.
https://github.com/hodgef/simple-keyboard/wiki/Roadmap

I can't guarantee a delivery date for this, but rest assured this is acknowledged and will ship soon.

Regards

**Comment by hodgef** [comment]
Hello @chhunchha,

I'm happy to announce that cursor position is now supported as of the latest version!

Try it out here:
[![Edit krzkx19rr](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/krzkx19rr)

Regards

**Comment by hodgef** [comment]
Hello @chhunchha,

I'm happy to announce that caret positioning is now supported on both simple-keyboard and react-simple-keyboard.

Check it out in action here:

[![Edit react-simple-keyboard demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m75m9v183p)https://codesandbox.io/s/m75m9v183p

Regards
