### ISSUE TITLE
Unable to call getInput function using Hooks

### ISSUE THREAD

**Issue by devbihari** [hodgef/react-simple-keyboard#511]
I'm not able to call keyboard.getInput() using hooks.
The error says: _keyboard.getinput() is not a function_
 I feel there is something I don't understand. Please help.

**Comment by hodgef** [comment]
Hey @devbihari,

In your error it says:
> keyboard.**getinput**() is not a function

if should be
> keyboard.**getInput**() (in camel case)

If you have typed it correctly please share more info, code, a screenshot, whatever might help.

Thanks,
Francisco Hodge

**Comment by devbihari** [comment]
Sorry I typed it incorrectly. 
This is the code snipped

```js
const keyboard = useRef();
const setActiveInput = (inputName) => {
   setInputName(inputName)
}

useEffect(() => {
       let updatedInputObj = {
    ...input,
      [inputName]: keyboard.getInput()
}
    setInput(updatedInputObj)
  },  [inputName])
```

The reason I'm trying to do it this way is because for some reason the OnChange method is not getting called on `<input>` with the react-simple-keyboard. However, it gets called when I press any key on the physical keyboard. So I'm trying to grab the input directly from the keyboard instead of relying on onChange.
Not sure if I'm doing something wrong.

Here is the snapshot of the error:
![bug](https://user-images.githubusercontent.com/26526504/78467602-e0f9fc80-772b-11ea-8c27-1790370d7304.png)

**Comment by hodgef** [comment]
Unfortunately I don't quite understand what you're trying to accomplish here.

The input's `onChange` will not be called when you type with simple-keyboard. Simple-keyboard's own `onChange` method will. Please follow [the react demo](https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-hooks-demo/tree/master/?from-embed) closely (In that demo, look for the `onChange`, `onChangeInput` functions).

One thing that I wanted to note though, this pattern
```
let updatedInputObj = {
...input,
[inputName]: keyboard.getInput()
};
setInput(updatedInputObj);
```
... can cause you problems. I recommend you get the previous value from the hook itself.

```
setInput(prevItems => {...prevItems, myNewItem});
```
 
If you're still stuck, I would need to debug a reproducible example of this issue. For this you just have to edit the following demo so it shows the issue and pass me the new link.

https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-hooks-demo/tree/master/?from-embed

Thanks,
Francisco Hodge

**Comment by devbihari** [comment]
I'm trying to reproduce class implementation of handling multiple inputs using hooks. I followed this [demo](https://franciscohodge.com/projects/react-simple-keyboard/demos/multiple-inputs-demo/). Additionally I was able to fix the previous error by replacing `keyboard.getInput()` with `keyboard.current.getInput()` but I'm still unable to achieve multiple input handling using single keyboard. I would be grateful if you could point me to some demo that uses hooks to handle multiple inputs.

Regards,
Amit Jha

**Comment by hodgef** [comment]
Sure! Here's a multiple inputs hooks demo:

https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-hooks-multiple-inputs/tree/master/

Regards,
Francisco Hodge

**Comment by devbihari** [comment]
Thanks @hodgef I was able to make the keyboard work with react and electron.

Regards,
Amit Jha
