### ISSUE TITLE
custom button label and value

### ISSUE THREAD

**Issue by mbretter** [hodgef/react-simple-keyboard#536]
**Is your feature request related to a problem? Please describe.**
When adding a custom button is there any possibility to define the value which will be written into the input box?
I've added a new button named "clear", within the onKeyPress event I'm handling the action (clearing the input field in this case), but the keyboard writes the name of the button into the input field.

**Describe the solution you'd like**
Distinguishing between label and value for a button, or adding the possibility to change the value inside the onKeyPress event handler, or stopping the default action for a button. Currently the click event object is not passed to onKeyPress, there is no possibility to stop the event propagation.

**Describe alternatives you've considered**
non

**Additional context**
none

**Comment by hodgef** [comment]
This seems to work for me:
https://codesandbox.io/s/delicate-currying-0t55h?file=/src/index.js

While [`clearInput`](https://simple-keyboard.com/documentation/#clearInput) clears the keyboard's buffer, you'd also have to clear the DOM input directly.

Regards,
Francisco Hodge

**Comment by mbretter** [comment]
thanx, that was the trick ...

cheers
