### ISSUE TITLE
Rows are being re-mounted on each re-render

### ISSUE THREAD

**Issue by QuentinRoy** [hodgef/react-simple-keyboard#549]
**React-simple-keyboard version**
2.3.4

**Describe the bug**
Since the new version, rows are being de-mounted and re-mounted every time the keyboard is re-rendered. This is not very efficient, but more annoying, the active state of a pressed button do not work anymore if you re-render the keyboard on each key press (e.g. because an input state has been updated which I expect is a very common use case).
I downgraded to 2.2.83, and everything is back to normal.

**Comment by hodgef** [comment]
Hello @QuentinRoy,

This is due to the fix for #545. If you turn debugging on (`debug={true}`) you can see in the logs what prop is causing the re-render and adjust accordingly.

Regards,
Francisco Hodge

**Comment by QuentinRoy** [comment]
I see. I am not quite convinced rows need to be unmounted when this happen. Changing function handlers is very common in react, you do expect components to be re-rendered, but not re-mounted.

**Comment by hodgef** [comment]
I think the fix to this would indeed be to only re-render the buttons when an option that requires it is changed. I'll look into fixing this in the core js library to see if it helps.

Thanks!

**Comment by QuentinRoy** [comment]
If this of any help, here is how I fixed it with `2.3.4`:
```js
    // Put the changing handlers in a ref updated at each render.
    const callbacksRef = useRef({});
    callbacksRef.current = { onKeyPress, onKeyRelease };

    // Create non changing callbacks that calls the changing ones.
    const handleKeyPress = useCallback((...args) => {
      if (callbacksRef.current.onKeyPress != null) {
        callbacksRef.current.onKeyPress(...args);
      }
    }, []);
    const handleKeyRelease = useCallback((...args) => {
      if (callbacksRef.current.onKeyRelease != null) {
        callbacksRef.current.onKeyRelease(...args);
      }
    }, []);
```

**Comment by hodgef** [comment]
Thanks! I think I'll fix it here:
https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.js#L483

Basically in the core library whenever _any_ option (or prop in this case) is changed, the rows are recreated. I'll try to restrict the number of options that can trigger a re-render.

I'll keep this ticket updated as I progress. Thanks again

**Comment by hodgef** [comment]
@QuentinRoy Should now be fixed as of 2.3.5. I'll deprecate versions 2.3.0-2.3.4.

Thanks again for reporting this bug.
Francisco Hodge

**Comment by QuentinRoy** [comment]
Amazing! Thanks!

**Comment by QuentinRoy** [comment]
FYI, my hacky fix was not such a good idea: https://twitter.com/dan_abramov/status/1253663995749453825
