### ISSUE TITLE
Unable to clear multiple inputs with a button click

### ISSUE THREAD

**Issue by devbihari** [hodgef/react-simple-keyboard#558]
I have been trying to clear multiple input fields with one button press but I have not been able to achieve it. However, I have no issues clearing single input box with a button click. 
I'm not sure if this is a bug or I'm missing something. 

Here are the screenshots:
![Screenshot from 2020-04-27 23-49-28](https://user-images.githubusercontent.com/26526504/80407045-9a3e9300-88e2-11ea-864f-516bd421c611.png)
## **I want to clear all inputs when I press X**
![Screenshot from 2020-04-27 23-50-02](https://user-images.githubusercontent.com/26526504/80407042-99a5fc80-88e2-11ea-9976-86132eec90cc.png)
## **After I press X the input clears but**
![Screenshot from 2020-04-27 23-49-28](https://user-images.githubusercontent.com/26526504/80407045-9a3e9300-88e2-11ea-864f-516bd421c611.png)
## **When I try to type anything from the react-simple-keyboard the previous values appear again**
![Screenshot from 2020-04-27 23-50-40](https://user-images.githubusercontent.com/26526504/80407037-97dc3900-88e2-11ea-9036-b5e49200c5a3.png)

**Comment by hodgef** [comment]
Hello @devbihari,

`clearInput` just clears the current input (defined through the inputName option).
https://simple-keyboardcom/react/documentation/#clearInput

If you want to reset the keyboard's whole internal input, you can use replaceInput instead of clearInput.
>replaceInput replaces the entire internal input object. The difference with “setInput” is that “setInput” only changes a single key of the input object, while “replaceInput” replaces the full input object.
```
replaceInput({default: ""});
```

Note that you'll also have to clear any local input state in your application.

**Comment by devbihari** [comment]
Worked! :smiley: 

Thanks @hodgef
