### ISSUE TITLE
Change display values to accept other than string.

### ISSUE THREAD

**Issue by antoniobologna** [hodgef/react-simple-keyboard#6]
## Details ##
Current version: 1.6.1
React Version: 16.4.0

## Overview ##
Currently, when setting up the display alternatives for some of the buttons the usage is as follow:

```js
display={{
  '{bksp}': 'delete',
  '{enter}': '< enter',
  '{shift}': 'shift',
  ...
}}
```

This is great and very useful, however, one likely scenario is that it would be super useful to have images or HTML elements instead of just text. 

When looking at this line: 
https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.js#L427
it's clear that whatever value we assigned to any of the buttons in the display object, will be set as is, meaning that it will be assigned as an Object if given one, instead of or a properly set DOM element, besides strings (or any other JS primitive form).

Is there any future plan to support this? I can gladly open up a PR if you're interested. Thanks :)

**Comment by hodgef** [comment]
Hello @antoniobologna,

Thank you for a nicely done bug report!

The issue with supporting HTML elements in my opinion is that it opens a pandora's box of potential buggy behavior. I think that the way to avoid all that would be to just add the images through CSS.

Looking at the `{enter}` key for example:

![image](https://user-images.githubusercontent.com/25509135/47127829-b9c01e80-d25c-11e8-8aad-b7a91c50b08c.png)

You could select it in CSS by:

`.hg-button-enter`
`[data-skbtn='{enter}']`
`[data-skbtnuid='r2b12']` (meaning the 12th button in the 2nd row)
`[data-displaylabel='< enter']`

There's also the [buttonTheme](https://github.com/hodgef/react-simple-keyboard#buttontheme) prop that lets you add a class of your choice to any button(s).

Here an example (with other approaches commented out):

[![Edit react-simple-keyboard-demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2xk0xolr10?module=%2Fsrc%2Findex.css)

_______________________________________

If you absolutely must add HTML to your buttons, there's a (not very react-like) escape hatch inherited from the core JS simple-keyboard package:

`this.keyboardRef.keyboard.getButtonElement("{enter}").innerHTML = ....`

But letting the CSS handle the images would definitely be my first option.

Please let me know if these currently available options could work for you. If not, feel free to tell me about other use-cases you feel should be covered and I'll reopen the ticket.

Thank you

**Comment by antoniobologna** [comment]
Hey, thanks for the quick reply @hodgef and yes absolutely this will work. Thanks again :)

**Comment by hodgef** [comment]
Hey @antoniobologna,

Just as an update, you are actually able to pass html code in the display prop, like this:

```
display={{
  '{bksp}': '<i class="fas fa-backspace"></i>',
  '{enter}': '<i class="fas fa-level-down-alt"></i>',
}}
```

![image](https://user-images.githubusercontent.com/25509135/49172020-dfd1e780-f30d-11e8-8c7a-037a1cbd9e07.png)

Regards :)

**Comment by antoniobologna** [comment]
oh wow, that seems great! Thanks for the update @hodgef.
