### ISSUE TITLE
Failed to get mock metadata

### ISSUE THREAD

**Issue by chapster11** [hodgef/react-simple-keyboard#618]
**React-simple-keyboard version**
Yes running the latest version

**Describe the bug**
I'm trying to test a component that has react-simple-keyboard imported into it. When I run my test I get the following error. 

`Failed to get mock metadata: C:\Users\myname\Documents\project\node_modules\react-simple-keyboard\build\index.js`

I'm using jest and enzyme. If I remove react-simple-keyboard from my test the component tests run correctly. 

I've tried multiple workarounds to this and running into a dead end. Hoping someone might have some insight into this.

**Comment by hodgef** [comment]
Hey @chapster11, do you mind providing a minimal repo to test/debug this? I'll close for now but reopen once I have it. Thanks!

**Comment by chapster11** [comment]
I wish I could be the project is so large. I'm trying to strip it down myself so yes I would close this if you don;t know of anything off hand. Do you have any test examples of the keyboard using Typescript ? 
Thanks for getting back so fast.

**Comment by hodgef** [comment]
Hey @chapster11, sadly I haven't encountered this before. I would need to debug it, but from past experience I found it more efficient to debug on user-provided repros (because then you are really sure you're repro'ing in the same env).

Here are some React TS demos:

**Demo with Hooks:**
https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/react-simple-keyboard-typescript-hooks/tree/master

(Github repo: https://github.com/simple-keyboard/react-simple-keyboard-typescript-hooks/tree/master/)

**Demo with Class component**
https://hodgef.com/simple-keyboard/editor/?d=hodgef/react-simple-keyboard-typescript-demos/tree/master

(Github repo: https://github.com/simple-keyboard/react-simple-keyboard-typescript-demos/tree/master)

Source: https://hodgef.com/simple-keyboard/getting-started/react/

**Comment by chapster11** [comment]
Thanks for the links. I have most of those from the site already. I did find this which was super helpful. 
https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js

One thing I noticed about the keyboard component which I love by they way. Is you can't pass it any regular props like id or data attributes. Or am I missing something ? 
For example: `<Keyboard } id="keyboard",  data-testid="keyboard" } />`
data-testid is what React-teat-library uses.

**Comment by hodgef** [comment]
Hmm no you're right, currently there's only [a way to add attributes to the buttons](https://hodgef.com/simple-keyboard/documentation/options/buttonattributes/).

For this react wrapper the "props" are actually [options passed directly to the core library](https://github.com/hodgef/react-simple-keyboard/blob/147835e74ec200faa556d1a65e066c3801ca91a5/src/lib/components/Keyboard.js#L21). So they don't make it to the element itself.

I think having a react-only `wrapperProps` option or something like that would be useful. Let me know if that's something you'd want to see and I'll work on it. Thanks!

**Comment by chapster11** [comment]
I think it would be a nice to have as far as React-test-library goes when unit testing but there are ways around it. I also think it would be nice to just give it an id if someone wanted. Again nice to have but the component works amazingly without it. 

I was having an issue with mocking out the component to return a ref and I think after seeing your link above and they way ref is passed on might be my problem. Sorry to diverge but it might be a  related in someway. 

```
jest.mock("react-simple-keyboard", () => ({
  default: () => <div>mock</div>,
  setInput: () => "test",
  __esModule: true,
}));
```
I'm not sure how I would get the ref to return from the mock above.

**Comment by hodgef** [comment]
Okay in that case it'll add to the Enhancements list :)

Could you provide a bit more context on what you're trying to accomplish overall with the ref? I'm not familiar with jest.mock but the deal with `keyboardRef` is that you pass a callback to it that fires on instantiation with the ref as param.

As you've prob seen here: https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js#L21

**Comment by chapster11** [comment]
jest.mock is a way of isolating a component inside your mocked component by mocking it instead of letting it run. 

Thanks for the link and fare enough if you haven't worked with that type of mock before. 

Like the idea of the Enhancements list.
