### ISSUE TITLE
Using one keyboard service instance with multiple inputs and components across an entire React application

### ISSUE THREAD

**Issue by BjoernKW** [hodgef/react-simple-keyboard#665]
**Is your feature request related to a problem? Please describe.**
While the [React example](https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/react-simple-keyboard-hooks-multiple-inputs) for multiple inputs given [here](https://hodgef.com/simple-keyboard/questions-answers/use-simple-keyboard-multiple-inputs/) works perfectly fine one has to duplicate those methods (_onChangeInput_, _onChangeAll_ etc.) in each component that makes use of simple-keyboard.

**Describe the solution you'd like**
I'd like a service that provides these methods so I don't have to duplicate code.

**Describe alternatives you've considered**
I've already tried using a custom useVirtualKeyboard() React Hook that supplies these methods. However, the reference to the keyboard and the input states get messed up with that approach, e.g. when focusing on a new input the values of the other inputs will be reset upon the first character being typed.

**Comment by hodgef** [comment]
Hello @BjoernKW,

The demos are really basic examples. They're just meant to explain the options so you can then develop a solution more to your needs.

For instance:
https://codesandbox.io/s/github/simple-keyboard/multiple-inputs-wrapper-router/tree/master/?file=/src/Home.js

Regards,
Francisco Hodge
