### ISSUE TITLE
While using keyboard input css element text goes out of bound. 

### ISSUE THREAD

**Issue by sanojKashyap** [hodgef/react-simple-keyboard#681]
React-simple-keyboard version: ^2.3.0 checked with previous version as well. Issue exists with 2.2.9.
While using keyboard input css element text goes out of bound. With hardware keyboard it is working fine. The issue with only app keyboard.

<img width="667" alt="Screenshot 2020-07-29 at 4 37 45 PM" src="https://user-images.githubusercontent.com/3175370/88793071-db806080-d1b9-11ea-9356-911ada106ff0.png">

CodeSandbox Link:
https://codesandbox.io/s/myp0l6xnj?file=/src/index.js:277-298

**Comment by hodgef** [comment]
Hello @sanojKashyap,

When you edit your input though Javascript (not only with simple-keyboard), the scrolling doesn't happen.

You'd have to scroll the input yourself like so:

React: 
https://github.com/simple-keyboard/react-simple-keyboard-uc-45-scroll-input-overflow-preventMouseDownDefault

Vanilla JS:
https://codesandbox.io/s/github/simple-keyboard/simple-keyboard-uc-45-scroll-input-overflow-preventMouseDownDefault

Regards,
Francisco Hodge

**Comment by sanojKashyap** [comment]
@hodgef If there are multiple input element, then how we handle in keyboard handler? 'onchange' method  // $(":input").onchnage("change", function() {} not working in this case with virtual keyboard. any help?

**Comment by hodgef** [comment]
If you are using React you can follow the React demo above, but if you're using jQuery you'll have to edit the Vanilla JS demoalso linked above:

For example, in the Vanilla JS demo you'll find :
```
document.querySelector(".input").addEventListener("input", event => {
  keyboard.setInput(event.target.value);
});
```

This is basically the onChange listener, but using standard JS instead of jQuery (notice the document.querySelector instead of `$()`.

Regards,
Francisco Hodge
