### ISSUE TITLE
Keypad not showing when wrapped inside a Dialog Modal in a React component

### ISSUE THREAD

**Issue by vinesh89** [hodgef/react-simple-keyboard#744]
In my React.js functional component i have the following components being rendered

`return (
    <div>
      <CustomKeyboard baseClass="keypad1" />
      <Dialog
        fullScreen
        onClose={handleClose}
        open={open}
      >
        <DialogTitle id="simple-dialog-title">Set backup account</DialogTitle>
        <List>
          <CustomKeyboard baseClass="keypad2" />
        </List>
      </Dialog>
    </div>
  );`

First up the react-simple-keyboard is rendered no issues, then when i open the dialog i need to again show the react-simple-keyboard which is wrapped inside my Dialog component, here the keypad is not being shown.

Am not sure what i am missing here, please help me out.

Here is the codesandbox link of this example, currently i am facing a similar issue in my project.
[https://codesandbox.io/s/material-demo-forked-dhzhu?file=/demo.js:1263-2439](url)

**Comment by hodgef** [comment]
Hello @vinesh89, it seems you're not passing the `baseClass` property to your keyboard component.

![image](https://user-images.githubusercontent.com/25509135/92122505-8099e480-edc9-11ea-8b99-16ca0b769a53.png)

If you pass that property to simple-keyboard I think your problem will be resolved.
https://hodgef.com/simple-keyboard/documentation/options/baseclass/

Regards,
Francisco Hodge

**Comment by vinesh89** [comment]
@hodgef Thank you so much
