### ISSUE TITLE
Backspace button does not work when an input with initial state is edited

### ISSUE THREAD

**Issue by KevinHernandez8** [hodgef/react-simple-keyboard#757]
**React-simple-keyboard version**: 2.3.72

**bug**
I implemented the keyboard and multiple inputs, one of them, with an initial state. When I edit the text field (it has initial state), the backspace button does not work. Here is the [example](https://codesandbox.io/s/xenodochial-tereshkova-6rvu8?file=/src/index.tsx)

![2020-09-08_12h54_56](https://user-images.githubusercontent.com/33167256/92511133-83824400-f1d2-11ea-9277-ababe4cfebb1.gif)

**Comment by hodgef** [comment]
Hello @KevinHernandez8,

You'd need to tell simple-keyboard that an input has a default value, by using either [setInput](https://hodgef.com/simple-keyboard/documentation/methods/setinput/) or [replaceInput](https://hodgef.com/simple-keyboard/documentation/methods/replaceinput/).

Here's an example:
https://codesandbox.io/s/awesome-voice-olnpz?file=/src/index.tsx

Regards,
Francisco Hodge
