### ISSUE TITLE
getCaretPosition regression v2.4

### ISSUE THREAD

**Issue by zprjk** [hodgef/react-simple-keyboard#788]
**React-simple-keyboard version**
v2.4.34

**Describe the bug**
While trying to simulate a _Mobile_ 'shift' experience, Only the **next** keystroke will be capitalized, I've encountered a problem that previously (v2.3.X) didn't had.

Here's a demo:
https://codesandbox.io/s/simple-keyboard-caretposition-regression-uy20m

Not sure if has to do with `getCaretPosition` so feel free to change the title accordingly.

**Screenshots**
Made a video to showcase the bug:
https://streamable.com/pb3q1m

Many thanks.

**Comment by zprjk** [comment]
I was able to reproduce this in vanilla:
https://codesandbox.io/s/simple-keyboard-caretposition-vanilla-1bexl

So this not related to simple-keyboard React port.

**Comment by hodgef** [comment]
Thanks a lot for the report @zprjk - This is probably related to https://github.com/hodgef/simple-keyboard/issues/695 - I'll investigate later today and work on a fix

**Comment by hodgef** [comment]
Hello @zprjk,

This should now be fixed on react-simple-keyboard 2.4.35. Feel free to give it a try.

Thanks!
Francisco Hodge
