### ISSUE TITLE
Question: how to (programattically) trigger a 'shift' key-press ?

### ISSUE THREAD

**Issue by dhowe** [hodgef/react-simple-keyboard#79]
I'm sure this already possible, but couldn't find it in the documentation. The use-case is that the user needs to type in their name with first-letter-capitalized, so we want the keyboard to start off as if shift key had been pressed. Then after the first typed character it should return to normal (as it does with a manual press of 'shift'). thanks!

**Comment by hodgef** [comment]
Hello @dhowe,

This is an use-case that is not supported by default. However, you can achieve this easily by creating a [module](https://franciscohodge.com/projects/simple-keyboard/modules/), like so:

https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-autocaps-module/tree/master/

Hope that helps.

Regards,
Francisco Hodge
