### ISSUE TITLE
Multiple Keyboards on Page

### ISSUE THREAD

**Issue by andresamayadiaz** [hodgef/react-simple-keyboard#80]
**React-simple-keyboard version** 1.24.0

**Describe the bug**
I have a keyboard in one Component and if i try to open a Dialog (modal) on top that contains another one it does not show up. I see on the DOM the <div> created but with no styles and nothing inside.

**Screenshots**
Here is the main screen with the first keyboard working ok:
<img width="1428" alt="Captura de Pantalla 2019-06-07 a la(s) 20 00 35" src="https://user-images.githubusercontent.com/1015043/59140111-2e1c0f00-895f-11e9-88c8-acc9eefae759.png">

And this is the Dialog being shown that should contain another keyboard:
<img width="1427" alt="Captura de Pantalla 2019-06-07 a la(s) 20 00 43" src="https://user-images.githubusercontent.com/1015043/59140123-56a40900-895f-11e9-9c0d-c1af04ddcab4.png">

And this is another page using the same Dialog with the keyboard that shows it ok, the only difference is that this page does not have another keyboard shown on an upper component:
<img width="401" alt="Captura de Pantalla 2019-06-07 a la(s) 20 00 55" src="https://user-images.githubusercontent.com/1015043/59140132-71767d80-895f-11e9-9b92-65288e501e94.png">

**Comment by hodgef** [comment]
Hello @andresamayadiaz,

Are you using the `baseClass` prop to set different classes for each keyboard? If you don't, the keyboard instances will override each other.

Here are the docs entries:
https://franciscohodge.com/projects/react-simple-keyboard/qa-use-cases/#give-different-class-keyboard
https://franciscohodge.com/projects/react-simple-keyboard/documentation/#baseClass

Hope that helps!

Regards,
Francisco Hodge

**Comment by andresamayadiaz** [comment]
Thank You!! this was the problem, sorry to miss this part of documentation, and again thanks for the quick response.
