### ISSUE TITLE
InputMask, InputPatter priority

### ISSUE THREAD

**Issue by faceru** [hodgef/react-simple-keyboard#845]
Hello, is it possible to somehow fix the problem with the mask priority. If you use your mask, and try to correct the value not at the end, then the cursor jumps to the end. I understand this because InputMask and InputPattern are more important than value. It is possible to fix this or it is a nuance of your keyboard implementation.

**Comment by hodgef** [comment]
Hello @faceru,

The InputMask module doesn't support caret positioning at the moment. If you open your console you should see a warning regarding this.

https://github.com/simple-keyboard/simple-keyboard-input-mask/blob/ee8c264286f9eed40022502e833701546abed903/src/index.js#L15

When you pass the `disableCaretPositioning` option the module stops warning about the lack of support.

Caret positioning support for input mask would be something really nice to have. If someone wants to work on this, I would really appreciate it as I don't have much time for it.

Thanks!
Francisco Hodge
