### ISSUE TITLE
Doesnt work simple-keyboard on iframe

### ISSUE THREAD

**Issue by behzadsoleimani** [hodgef/react-simple-keyboard#873]
Ui on Our React Project open in a Frame (Iframe), but simple-keyboard crashed in Iframe probably because simple-keyboard search div with "simple-keyboard" class on window.document not Iframe content. please fix it.

**Comment by hodgef** [comment]
Hello @behzadsoleimani, please provide a repro sandbox or git repository that shows the issue. Thanks!

Per the bug template:
>**Describe the bug**
>A clear and concise description of what the bug is. **Providing a [sandbox example](https://codesandbox.io/s/new) or code depicting the issue is important, as this will help us reproduce the issue.**
