### ISSUE TITLE
When using key navigation, and clicking on left or up arrow the cursor moves also inside of the input field 

### ISSUE THREAD

**Issue by MarcoFiusco** [hodgef/react-simple-keyboard#878]
**React-simple-keyboard version**
2.3.143

**Describe the bug**
When writing on an input field using the keyboard key navigation, and clicking on the left or the up arrow, navigates correcly inside of the keyboard keys but also moves the cursor in the input field.

I.E.
When the input is empty I navigate to the W and click enter, the input now contains W. If I click on the left to enter also a Q and press enter. Now the input contains QW instead of WQ.

Do you know a workaround for this happening?
Thanks
Marco

**Comment by hodgef** [comment]
Hello @MarcoFiusco, if you want to prevent cursor movement in an input, you can use `preventDefault()` in your listener.

Here's more details:
https://stackoverflow.com/a/22384116/1467941

Regards,
Francisco Hodge
