### ISSUE TITLE
Keys are not getting clicked from console

### ISSUE THREAD

**Issue by chetrix** [hodgef/react-simple-keyboard#915]
Hi,
I have used your package react-simple-keyboard in my project. However, to implement automation testing or selenium, I am finding it difficult to implement click method on the keys.
For example 
if I enter the below statement on the console and by 5th element of <span> is '3' on the keyboard.

document.getElementsByTagName('span')[5].click();

'3' is not getting typed on the input field. 
can you please help?

**Comment by hodgef** [comment]
Hello @chetrix,

You might find react-simple-keyboard unit tests useful:
https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js#L103

Specifically clicking a button, like so:
```js
keyboard.getButtonElement("q").onclick();
```
https://hodgef.com/simple-keyboard/documentation/methods/getbuttonelement/

One thing to keep in mind is that simple-keyboard uses [`PointerEvents`](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) by default, so you might have to use `button.onpointerdown()` and `button.onpointerup()` instead.

If you would like to use mouse events, you can use the option [`useMouseEvents`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/).

Hope that helps,
Francisco Hodge

**Comment by chetrix** [comment]
thank you so much. it worked like a charm
