### ISSUE TITLE
Iframe

### ISSUE THREAD

**Issue by chetrix** [hodgef/react-simple-keyboard#932]
Hi, 
 Can we integrate the package with iframe? Can we use simple keyboard during the checkout page or payment page? Since checkout page is 3rd party page which we can interact within an iframe.

**Comment by hodgef** [comment]
Hello @chetrix,

As far as I know you can only interact with iframes from your same application (domain).

If you want to control an iframe that points to another domain, that'll usually end up failing unless the iframe target has whitelisted your domain. This is a security feature enforced by the browser.

>The “Same Origin” policy states that:
>
>  -  if we have a reference to another window, e.g. a popup created by window.open or a window inside <iframe>, and that window comes from the same origin, then we have full access to that window.
>  -  otherwise, if it comes from another origin, then **we can’t access the content of that window: variables, document, anything.** The only exception is location: we can change it (thus redirecting the user). But we cannot read location (so we can’t see where the user is now, no information leak).

https://javascript.info/cross-window-communication#same-origin

Regards,
Francisco Hodge
