### ISSUE TITLE
how to use formik and react-simple-keyboard together

### ISSUE THREAD

**Issue by darda-ergo** [hodgef/react-simple-keyboard#958]
I am using formik to handle form my react project and i need to use react-simple-keyboard. How can I use both libraries together? Any idea or demo will help. Thank you

**Comment by hodgef** [comment]
Hello @darda-ergo,

That's probably a question you'd have to ask to the mantainers of Formik. I'm personally not quite familiar with it.

As far as simple-keyboard is concerned:

- It outputs through [`onKeyPress`](https://hodgef.com/simple-keyboard/documentation/options/onkeypress/), [`onChange`](https://hodgef.com/simple-keyboard/documentation/options/onchange/) and [`keyboard.getInput()`](https://hodgef.com/simple-keyboard/documentation/methods/getinput/).
- It takes input through [`keyboard.setInput()`](https://hodgef.com/simple-keyboard/documentation/methods/setinput/) and [`keyboard.replaceInput()`](https://hodgef.com/simple-keyboard/documentation/methods/replaceinput/)

You would need to investigate whether Formik also provides a way (methods or props) to send in input and receive updated input programmatically, so you can do the syncing. The following would apply to any library you'd like to integrate, not just Formik.

Regards,
Francisco Hodge
