### ISSUE TITLE
How can I access keyboard key positions in terms of offsetLeft and offsetTop?

### ISSUE THREAD

**Issue by vardaro** [hodgef/react-simple-keyboard#960]
Hello,

I would like to be able to access the ```HTMLElement.offsetLeft``` and ```HTMLElement.offsetTop``` properties of each key in the keyboard. In other words, I would like be able to identify the pixel coordinates that correspond to the top-left corner of each key.

Is there a supported or conventional approach to extracting this info from the keyboard keys?

Thank you so much,

Anthony

**Comment by hodgef** [comment]
Hello @vardaro,

You can probably use the method `recurseButtons` for this task. It's a ForEach to iterate through all the buttons.

Use it like so (with `keyboard.current` in case you're using React Hooks):
```
keyboard.current.recurseButtons(buttonElement => {
  // Use buttonElement as needed
});
```
https://hodgef.com/simple-keyboard/documentation/methods/recursebuttons/

Regards,
Francisco Hodge
