### ISSUE TITLE
Do you have any suggestions for referencing the keyboard globally?(React)

### ISSUE THREAD

**Issue by skyunBoss** [hodgef/react-simple-keyboard#964]
React I want to click the input in the project to directly pop up the keyboard instead of introducing no components

Vue can be two-way binding

**Comment by hodgef** [comment]
Hello @skyunBoss,

Here's an example of visibility toggling through onFocus and onBlur.
https://codesandbox.io/s/keen-einstein-ck99n?file=/src/index.tsx

Feel free to take this example and adapt it to your needs.

Regards,
Francisco Hodge
