### ISSUE TITLE
how I can add japanese

### ISSUE THREAD

**Issue by rustamveer** [hodgef/react-simple-keyboard#972]
I tried using https://hodgef.com/simple-keyboard/editor/?d=hodgef/react-simple-keyboard-demos/tree/master
but did not work/

`import React, { useRef, useState } from "react";
import ReactDOM from "react-dom";
import Head from 'next/head'
import Nav from "../components/nav"
import Keyboard from 'react-simple-keyboard';

import 'react-simple-keyboard/build/css/index.css';
export default function Home() {
  
  const [input, setInput] = useState("");
  const [layout, setLayout] = useState("default");
  const keyboard = useRef();

  const onChange = input => {
    setInput(input);
    console.log("Input changed", input);
  };

  const handleShift = () => {
    const newLayoutName = layout === "default" ? "shift" : "default";
    setLayout(newLayoutName);
  };

  const onKeyPress = button => {
    console.log("Button pressed", button);

    /**
     * If you want to handle the shift and caps lock buttons
     */
    if (button === "{shift}" || button === "{lock}") handleShift();
  };

  const onChangeInput = event => {
    const input = event.target.value;
    setInput(input);
    keyboard.current.setInput(input);
  };

  return (
    <>
          <Nav />
    <div className="container">
      <Head>
        <title>Typing Tool</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3 className="title">
          Welcome to my site!
        </h3>
   <input
        value={input}
        placeholder={"Tap on the virtual keyboard to start"}
        onChange={onChangeInput}
      />
      <Keyboard
        keyboardRef={r => (keyboard.current = r)}
        layoutName={layout}
        onChange={onChange}
        onKeyPress={onKeyPress}
      />`

**Comment by hodgef** [comment]
Hello @rustamveer,

Check out the Q&A section of the documentation:
https://hodgef.com/simple-keyboard/questions-answers/set-keys-different-language/

Regards,
Francisco Hodge

**Comment by rustamveer** [comment]
Hi Hodgef,

I looked at the Q&A and installed the required package, however, when I call that in my nextjs page, it gives me a syntax error

import layout from 'simple-keyboard-layouts/build/layouts/japanese';

`Server Error
SyntaxError: Unexpected token export

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
external%20%22simple-keyboard-layouts\build\layouts\japanese%22 (1:0) @ Object.simple-keyboard-layouts/build/layouts/japanese

> 1 | module.exports = require("simple-keyboard-layouts/build/layouts/japanese");`

Regards

**Comment by hodgef** [comment]
Hey @rustamveer,

That error is most likely related to your setup and not simple-keyboard. I think your best bet is to look up:
"SyntaxError: Unexpected token export nextjs"

This lead me to more information like the following:
https://github.com/GoogleChrome/web-vitals/issues/20#issuecomment-624406721

But you'll most likely have to double check with the nextjs mantainers to see how you can import something from node modules.

Regards,
Francisco Hodge
