### ISSUE TITLE
addButtonTheme() with React Hooks?

### ISSUE THREAD

**Issue by vardaro** [hodgef/react-simple-keyboard#986]
**React-simple-keyboard version**
```json
"react-simple-keyboard": "latest"
```

**Describe the bug**
I'd like to call ```addButtonTheme()``` in a function component using React Hooks. It seems as though I cannot get this function to affect the style of the keyboard in my codebase, or even the demo codebase hosted on the [official site.](https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/react-simple-keyboard-hooks-demo/tree/master)

Perhaps I am calling the function incorrectly.

**Screenshots**
Here is some example code that demonstrates the issue. It should look very similar to the code in the demo.

```jsx
// index.js
import React, { useRef, useState } from "react";
import ReactDOM from "react-dom";
import Keyboard from "react-simple-keyboard";
import "react-simple-keyboard/build/css/index.css";

import "./styles.css";

function App() {
  const [input, setInput] = useState("");
  const [layout, setLayout] = useState("default");
  const keyboard = useRef();

  const onChange = input => {
    setInput(input);
    console.log("Input changed", input);

   // I would like to change the background color of the last pressed key.
    let lastKey = input.slice(-1);
    keyboard.current.addButtonTheme(lastKey, "myClass");
  };

  const handleShift = () => {};

  const onKeyPress = button => {};

  const onChangeInput = event => {};

  return (
    <div className="App">
      <input
        value={input}
        placeholder={"Tap on the virtual keyboard to start"}
        onChange={onChangeInput}
      />
      <Keyboard
        keyboardRef={r => (keyboard.current = r)}
        layoutName={layout}
        onChange={onChange}
        onKeyPress={onKeyPress}
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

```css
// styles.css
.simple-keyboard {
  max-width: 850px;
}

.myClass {
  background-color: red;
}
```

Thanks for your help,

Anthony

**Comment by hodgef** [comment]
Hello @vardaro,

I would recommend to instead use `buttonTheme` in a React environment.

Check out the `buttonTheme` usage in the following sandbox:
https://codesandbox.io/s/github/hodgef/react-simple-keyboard-demos/tree/uc-customization/?from-embed

Here you'll find another example using hooks:
https://github.com/hodgef/react-simple-keyboard/issues/837

Regards,
Francisco Hodge

**Comment by vardaro** [comment]
Hey Francisco,

Thanks for your patience. I was able to fit your example to my use case.

Thanks,

Anthony
