### ISSUE TITLE
how handle a large form by react-simple-key in more perfect way 

### ISSUE THREAD

**Issue by darda-ergo** [hodgef/react-simple-keyboard#990]
I am having trouble while i am showing the virtual keyboard at bottom of a large form. Coz when i select a form field i have to at the bottom of the form to type on the virtual keyboard every time. Can i show the keyboard after every selected form input.

Right now my form is looking like this..
![image](https://user-images.githubusercontent.com/61325474/105447841-38f3f680-5c9f-11eb-821c-62d02414b333.png)

**Comment by hodgef** [comment]
Hello @darda-ergo,

To accomplish this you'd need to instantiate the keyboard under your input (So for example you'd have an InputKeyboard component with both the input and the keyboard - the latter to be shown on input focus).

Another, more complex way would be or use [`Element.getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) in your input's onFocus to get its coordinates, then to move the keyboard to that position.

Ultimately though, leaving the keyboard at the bottom (with **`position: fixed`**`) is the standard approach (if you look at for example the Windows and iOS virtual keyboards, they're all on the bottom.)

![maxresdefault](https://user-images.githubusercontent.com/25509135/105513410-45c51a00-5ca0-11eb-9d19-9661af659c63.jpg)
![1200px-Apple_iPad_Event03](https://user-images.githubusercontent.com/25509135/105513421-48277400-5ca0-11eb-80ef-4cb10540535e.jpg)
