### ISSUE TITLE
Keyboard is hiding every time i am clicking on the virtual keyboard

### ISSUE THREAD

**Issue by darda-ergo** [hodgef/react-simple-keyboard#993]
I am handling a large form so i need to hide the keyboard while the input field is onBlur state. But every time i press a key on virtual keyboard the input is onBlur state but i want it only after i finish type my full input rather than a single key. What to do?
this is my part of code .

.simple-keyboard {
  max-width: 50vw;
  z-index: 10;
  position: fixed;
  bottom: 0;
}
  const handleFocus = (e) => {
    setFormError(initialErrors);
    setInputName(e.target.name);
    setShowKeyBoard(true);
  };

    <label>unit:</label>
            <input
              id="unit"
              type="text"
              name="unit"
              className="form-control"
              placeholder="Unit Number"
              onChange={onChangeInput}
              value={inputs.unit}
              onFocus={handleFocus}
              onBlur={() => setShowKeyBoard(false)}
            />

      <div
        styel={{ position: "fixed", bottom: 0 }}
        className={`${showKeyboard ? "keyboard-show" : "keyboard-hidden"}`}
      >
        <Keyboard
          keyboardRef={(r) => (keyboard.current = r)}
          inputName={inputName}
          layoutName={layoutName}
          onChangeAll={onChangeAll}
          onKeyPress={onKeyPress}
        />
      </div>
![keyboard](https://user-images.githubusercontent.com/61325474/105677140-b32db080-5f15-11eb-9eb9-e2e35bbf5415.gif)

**Comment by hodgef** [comment]
Hello @darda-ergo,

You can use a ["onClickOutside" library](https://material-ui.com/components/click-away-listener/) to detect whether you're clicking outside of the keyboard. You can then use this information to improve the check in your input's `onBlur`.

Regards,
Francisco Hodge
