### ISSUE TITLE
Virtual Keyboard  providing 0 value after press backspace

### ISSUE THREAD

**Issue by darda-ergo** [hodgef/react-simple-keyboard#999]
my code is working with the normal keyboard but while i am using the virtual keyboard the backspace is not working even after  i am using replaceinput() . 

![simle key borad issue](https://user-images.githubusercontent.com/61325474/106563526-180c8a80-6556-11eb-9a79-f8e43c30b63f.gif)

this is my code..

import { makeStyles } from "@material-ui/core/styles";
import React, { useEffect, useRef, useState } from "react";
import { confirmAlert } from "react-confirm-alert";
import { Link, useHistory } from "react-router-dom";
import Keyboard from "react-simple-keyboard";
import { toast } from "react-toastify";
import axios from "../../../axios";
import AlertBar from "../../AlertBar/AlertBar";
import { H1, H3, PrimaryButton } from "../../cssComponents/CssComponents";

const useStyles = makeStyles((theme) => ({
  select: {
    minWidth: 120,
    background: "#eee",
    margin: "0 20px",
    borderRadius: "5px",
    padding: 5,
  },
  selectContainer: {
    display: "flex",
  },
  priceContainer: {
    display: "flex",
    margin: "20px 0",
    justifyContent: "space-between",
    alignItems: "center",
  },
}));

function PrivateLockerRate() {
  const classes = useStyles();
  const history = useHistory();

  // const { usageData } = useContext(RootContext);
  // let id = null;
  // let unit_value = null;
  // let durationPub = null;
  // let unit_name = null;
  // if (usageData.length === 1) {
  //   id = usageData[0].id;
  //   unit_value = usageData[0].unit_value;
  //   durationPub = usageData[0].duration;
  //   unit_name = usageData[0].unit_name;
  // }
  // console.log("usage data", usageData);
  const initialValues = {
    duration: "",
    unit_value: "",
  };
  const [layoutName, setLayoutName] = useState("default");
  const [inputName, setInputName] = useState("duration");
  const [inputs, setInputs] = useState(initialValues);

  const [showKeyboard, setShowKeyBoard] = useState(false);

  const [unitName, setUnitName] = useState("hour");
  // const [duration, setDuration] = useState(durationPub || "");
  // const [amount, setAmount] = useState(unit_value || "");
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState("");
  const [usageData, setUsageData] = useState([]);
  const [firstLoading, setFirstLoading] = useState(false);
  const [id, setId] = useState();
  async function fetchUsageApi() {
    try {
      setFirstLoading(true);
      const result = await axios.get(`/configuration/usage`);
      console.log("USage Api", result);
      const { status, data } = result;

      setUsageData(result.data[0]);

      setUnitName(data[0].unit_name);
      setInputs({
        ...inputs,
        duration: data[0].duration,
        unit_value: data[0].unit_value,
      });
      setId(data[0].id);
      setFirstLoading(false);
      // setLoader(true);
    } catch (e) {
      setFirstLoading(false);
      // setLoader(false);
      console.log("error response", e.response);
    }
  }

  const keyboard = useRef();
  const inputRef = useRef();
  const handleShift = () => {
    const newLayoutName = layoutName === "default" ? "shift" : "default";
    setLayoutName(newLayoutName);
  };

  const onKeyPress = (button) => {
    console.log("Button pressed", button);
    if (button === "{shift}" || button === "{lock}") handleShift();
  };

  const onChangeInput = (event) => {
    const inputVal = event.target.value;
    console.log("inpuVAl", keyboard.current);

    keyboard.current.setInput(inputVal);
    setInputs({
      ...inputs,
      [event.target.name]: event.target.value,
    });
  };

  const onChangeAll = (inputs) => {
    setInputs({ ...inputs });
    console.log("Inputs changed", inputs);
  };

  const handleFocus = (e) => {
    setInputName(e.target.name);
    setShowKeyBoard(true);
  };
  // formData.append("unit_name", unitValue);
  // formData.append("duration", inputs.duration);
  // formData.append("unit_value", inputs.amount);

  const handleSubmit = (e) => {
    e.preventDefault();
    const formData = new FormData();
    formData.append("unit_name", unitName);
    formData.append("duration", inputs.duration);
    formData.append("unit_value", inputs.unit_value);
    async function postUsageApi() {
      setLoading(true);
      try {
        const result = await axios.post(`/configuration/usage/new/`, formData);
        console.log("Usage post Api", result);
        const { status } = result;
        if (status === 201) {
          toast.success("Usage Configuration Completed!");
          history.push({ pathname: "/commands" });
        }
      } catch (e) {
        setLoading(false);
        console.log("error response", e.response);
      }
    }
    async function putUsageApi() {
      try {
        setLoading(true);
        const result = await axios.put(`/configuration/usage/${id}`, formData);
        // console.log("Usage put Api", result);
        const { status } = result;
        if (status === 200) {
          toast.success("Usage Configuration Updated!");
          history.push({ pathname: "/commands" });
        }
      } catch (e) {
        setLoading(false);
        console.log("error response", e.response);
      }
    }
    if (!id) {
      postUsageApi();
    }
    if (id) {
      putUsageApi();
    }
  };
  const handleError = () => {
    setErrors("");
  };
  const onHelpClick = () => {
    confirmAlert({
      title: "Help Center",
      message: "Take the following steps :",
      buttons: [
        {
          label: "Okay",
        },
      ],

      customUI: ({ onClose }) => (
        <div className="helpCenterDiv">
          <H3>Help Center</H3>
          <p>Take the following steps :</p>
          <PrimaryButton onClick={onClose}>Okay</PrimaryButton>
        </div>
      ),
    });
  };
  console.log("inputssss", inputs);
  useEffect(() => {
    keyboard.current.replaceInput(inputs);
    fetchUsageApi();
  }, []);
  return (
    <div className="body-container">
      <H1>Configure Usage</H1>

      <div className="subContainer">
        {errors ? <AlertBar handleError={handleError} /> : null}

        <div className={classes.priceContainer}>
          <label style={{ marginRight: "10px" }}>Unit :</label>
          <div className="clearfix">
            <select
              value={unitName}
              onChange={(e) => {
                setUnitName(e.target.value);
              }}
            >
              <option value={"hour"}>Hour</option>
              <option value={"week"}>Week</option>
            </select>
          </div>
        </div>
        <div className={classes.priceContainer} style={{ marginLeft: "85px" }}>
          <label>Maximum Duration:</label>
          <div className="form-group">
            <input
              style={{ width: "100px", margin: "0 10px" }}
              id="duration"
              name="duration"
              type="text"
              className="form-control"
              onFocus={handleFocus}
              value={inputs.duration}
              onChange={onChangeInput}
            />
          </div>

          <span>X Unit Time</span>
        </div>
        <div className={classes.priceContainer} style={{ marginLeft: "160px" }}>
          <label>Rate:</label>

          <input
            style={{ width: "100px", margin: "0 10px" }}
            id="unit_value"
            value={inputs.unit_value}
            onChange={onChangeInput}
            onFocus={handleFocus}
            name="unit_value"
            type="text"
            className="form-control"

            // placeholder="Rate"
          />

          <span>/ Unit Time / Unit Size</span>
        </div>
        <div className="buttonParentContainer ">
          <div className="buttonContainer" style={{ width: "40vw" }}>
            <PrimaryButton className="" onClick={handleSubmit}>
              {loading ? "saving.." : " Save"}
            </PrimaryButton>
            <PrimaryButton className="" onClick={onHelpClick}>
              Help
            </PrimaryButton>
            <Link to="/commands" style={{ textDecoration: "none" }}>
              <PrimaryButton className="">Cancel</PrimaryButton>
            </Link>
          </div>
        </div>
      </div>
      <div className={`${showKeyboard ? "keyboard-show" : "keyboard-hidden"}`}>
        <Keyboard
          keyboardRef={(r) => (keyboard.current = r)}
          inputName={inputName}
          layoutName={layoutName}
          onChangeAll={onChangeAll}
          onKeyPress={onKeyPress}
        />
      </div>
    </div>
  );
}

export default PrivateLockerRate;

**Comment by hodgef** [comment]
Hello @darda-ergo,

Could you provide a reproducible example of the issue? This will allow me to debug this. You can for example take one of the react demos, edit it and provide its new link - or you can provide a test git repository that shows the issue.

Regards,
Francisco Hodge
